// Generated at Tue Jun 12 15:21:45 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.demogrp;

public class DemoGroup$PopupForm1 extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $1_1$ConstantFormField;
	public egl.ui.text.TuiField $15_1$ConstantFormField;
	public egl.ui.text.TuiField $4_1$ConstantFormField;
	public egl.ui.text.TuiField $12_1$ConstantFormField;
	public egl.ui.text.TuiField $2_1$ConstantFormField;
	public egl.ui.text.TuiField $2_41$ConstantFormField;
	public egl.ui.text.TuiField $3_1$ConstantFormField;
	public egl.ui.text.TuiField $3_41$ConstantFormField;
	public egl.ui.text.TuiField $5_1$ConstantFormField;
	public egl.ui.text.TuiField $5_41$ConstantFormField;
	public egl.ui.text.TuiField $6_1$ConstantFormField;
	public egl.ui.text.TuiField $6_41$ConstantFormField;
	public egl.ui.text.TuiField $7_1$ConstantFormField;
	public egl.ui.text.TuiField $7_41$ConstantFormField;
	public egl.ui.text.TuiField $8_1$ConstantFormField;
	public egl.ui.text.TuiField $8_41$ConstantFormField;
	public egl.ui.text.TuiField $9_1$ConstantFormField;
	public egl.ui.text.TuiField $9_41$ConstantFormField;
	public egl.ui.text.TuiField $10_1$ConstantFormField;
	public egl.ui.text.TuiField $10_41$ConstantFormField;
	public egl.ui.text.TuiField $11_1$ConstantFormField;
	public egl.ui.text.TuiField $11_41$ConstantFormField;
	public egl.ui.text.TuiField $13_1$ConstantFormField;
	public egl.ui.text.TuiField $13_41$ConstantFormField;
	public egl.ui.text.TuiField $14_1$ConstantFormField;
	public egl.ui.text.TuiField $14_41$ConstantFormField;
	
	public DemoGroup$PopupForm1( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$1_1$ConstantFormField = new egl.ui.text.TuiField( "$1_1$ConstantFormField", this, null );
		$1_1$ConstantFormField.setPosition(0,1,1);
		$1_1$ConstantFormField.setCurrentValue(0,"-----------------------------------------",true);
		$1_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$1_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$1_1$ConstantFormField.setIsComplete();
		addField( $1_1$ConstantFormField );
		$15_1$ConstantFormField = new egl.ui.text.TuiField( "$15_1$ConstantFormField", this, null );
		$15_1$ConstantFormField.setPosition(0,15,1);
		$15_1$ConstantFormField.setCurrentValue(0,"-----------------------------------------",true);
		$15_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$15_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_1$ConstantFormField.setIsComplete();
		addField( $15_1$ConstantFormField );
		$4_1$ConstantFormField = new egl.ui.text.TuiField( "$4_1$ConstantFormField", this, null );
		$4_1$ConstantFormField.setPosition(0,4,1);
		$4_1$ConstantFormField.setCurrentValue(0,"-----------------------------------------",true);
		$4_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$4_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$4_1$ConstantFormField.setIsComplete();
		addField( $4_1$ConstantFormField );
		$12_1$ConstantFormField = new egl.ui.text.TuiField( "$12_1$ConstantFormField", this, null );
		$12_1$ConstantFormField.setPosition(0,12,1);
		$12_1$ConstantFormField.setCurrentValue(0,"-----------------------------------------",true);
		$12_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$12_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$12_1$ConstantFormField.setIsComplete();
		addField( $12_1$ConstantFormField );
		$2_1$ConstantFormField = new egl.ui.text.TuiField( "$2_1$ConstantFormField", this, null );
		$2_1$ConstantFormField.setPosition(0,2,1);
		$2_1$ConstantFormField.setCurrentValue(0,"|",true);
		$2_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$2_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$2_1$ConstantFormField.setIsComplete();
		addField( $2_1$ConstantFormField );
		$2_41$ConstantFormField = new egl.ui.text.TuiField( "$2_41$ConstantFormField", this, null );
		$2_41$ConstantFormField.setPosition(0,2,41);
		$2_41$ConstantFormField.setCurrentValue(0,"|",true);
		$2_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$2_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$2_41$ConstantFormField.setIsComplete();
		addField( $2_41$ConstantFormField );
		$3_1$ConstantFormField = new egl.ui.text.TuiField( "$3_1$ConstantFormField", this, null );
		$3_1$ConstantFormField.setPosition(0,3,1);
		$3_1$ConstantFormField.setCurrentValue(0,"|",true);
		$3_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$3_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_1$ConstantFormField.setIsComplete();
		addField( $3_1$ConstantFormField );
		$3_41$ConstantFormField = new egl.ui.text.TuiField( "$3_41$ConstantFormField", this, null );
		$3_41$ConstantFormField.setPosition(0,3,41);
		$3_41$ConstantFormField.setCurrentValue(0,"|",true);
		$3_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$3_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_41$ConstantFormField.setIsComplete();
		addField( $3_41$ConstantFormField );
		$5_1$ConstantFormField = new egl.ui.text.TuiField( "$5_1$ConstantFormField", this, null );
		$5_1$ConstantFormField.setPosition(0,5,1);
		$5_1$ConstantFormField.setCurrentValue(0,"|",true);
		$5_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$5_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_1$ConstantFormField.setIsComplete();
		addField( $5_1$ConstantFormField );
		$5_41$ConstantFormField = new egl.ui.text.TuiField( "$5_41$ConstantFormField", this, null );
		$5_41$ConstantFormField.setPosition(0,5,41);
		$5_41$ConstantFormField.setCurrentValue(0,"|",true);
		$5_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$5_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_41$ConstantFormField.setIsComplete();
		addField( $5_41$ConstantFormField );
		$6_1$ConstantFormField = new egl.ui.text.TuiField( "$6_1$ConstantFormField", this, null );
		$6_1$ConstantFormField.setPosition(0,6,1);
		$6_1$ConstantFormField.setCurrentValue(0,"|",true);
		$6_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$6_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_1$ConstantFormField.setIsComplete();
		addField( $6_1$ConstantFormField );
		$6_41$ConstantFormField = new egl.ui.text.TuiField( "$6_41$ConstantFormField", this, null );
		$6_41$ConstantFormField.setPosition(0,6,41);
		$6_41$ConstantFormField.setCurrentValue(0,"|",true);
		$6_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$6_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_41$ConstantFormField.setIsComplete();
		addField( $6_41$ConstantFormField );
		$7_1$ConstantFormField = new egl.ui.text.TuiField( "$7_1$ConstantFormField", this, null );
		$7_1$ConstantFormField.setPosition(0,7,1);
		$7_1$ConstantFormField.setCurrentValue(0,"|",true);
		$7_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$7_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_1$ConstantFormField.setIsComplete();
		addField( $7_1$ConstantFormField );
		$7_41$ConstantFormField = new egl.ui.text.TuiField( "$7_41$ConstantFormField", this, null );
		$7_41$ConstantFormField.setPosition(0,7,41);
		$7_41$ConstantFormField.setCurrentValue(0,"|",true);
		$7_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$7_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_41$ConstantFormField.setIsComplete();
		addField( $7_41$ConstantFormField );
		$8_1$ConstantFormField = new egl.ui.text.TuiField( "$8_1$ConstantFormField", this, null );
		$8_1$ConstantFormField.setPosition(0,8,1);
		$8_1$ConstantFormField.setCurrentValue(0,"|",true);
		$8_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$8_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_1$ConstantFormField.setIsComplete();
		addField( $8_1$ConstantFormField );
		$8_41$ConstantFormField = new egl.ui.text.TuiField( "$8_41$ConstantFormField", this, null );
		$8_41$ConstantFormField.setPosition(0,8,41);
		$8_41$ConstantFormField.setCurrentValue(0,"|",true);
		$8_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$8_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_41$ConstantFormField.setIsComplete();
		addField( $8_41$ConstantFormField );
		$9_1$ConstantFormField = new egl.ui.text.TuiField( "$9_1$ConstantFormField", this, null );
		$9_1$ConstantFormField.setPosition(0,9,1);
		$9_1$ConstantFormField.setCurrentValue(0,"|",true);
		$9_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$9_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_1$ConstantFormField.setIsComplete();
		addField( $9_1$ConstantFormField );
		$9_41$ConstantFormField = new egl.ui.text.TuiField( "$9_41$ConstantFormField", this, null );
		$9_41$ConstantFormField.setPosition(0,9,41);
		$9_41$ConstantFormField.setCurrentValue(0,"|",true);
		$9_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$9_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_41$ConstantFormField.setIsComplete();
		addField( $9_41$ConstantFormField );
		$10_1$ConstantFormField = new egl.ui.text.TuiField( "$10_1$ConstantFormField", this, null );
		$10_1$ConstantFormField.setPosition(0,10,1);
		$10_1$ConstantFormField.setCurrentValue(0,"|",true);
		$10_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$10_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_1$ConstantFormField.setIsComplete();
		addField( $10_1$ConstantFormField );
		$10_41$ConstantFormField = new egl.ui.text.TuiField( "$10_41$ConstantFormField", this, null );
		$10_41$ConstantFormField.setPosition(0,10,41);
		$10_41$ConstantFormField.setCurrentValue(0,"|",true);
		$10_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$10_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_41$ConstantFormField.setIsComplete();
		addField( $10_41$ConstantFormField );
		$11_1$ConstantFormField = new egl.ui.text.TuiField( "$11_1$ConstantFormField", this, null );
		$11_1$ConstantFormField.setPosition(0,11,1);
		$11_1$ConstantFormField.setCurrentValue(0,"|",true);
		$11_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$11_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_1$ConstantFormField.setIsComplete();
		addField( $11_1$ConstantFormField );
		$11_41$ConstantFormField = new egl.ui.text.TuiField( "$11_41$ConstantFormField", this, null );
		$11_41$ConstantFormField.setPosition(0,11,41);
		$11_41$ConstantFormField.setCurrentValue(0,"|",true);
		$11_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$11_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_41$ConstantFormField.setIsComplete();
		addField( $11_41$ConstantFormField );
		$13_1$ConstantFormField = new egl.ui.text.TuiField( "$13_1$ConstantFormField", this, null );
		$13_1$ConstantFormField.setPosition(0,13,1);
		$13_1$ConstantFormField.setCurrentValue(0,"|",true);
		$13_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$13_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_1$ConstantFormField.setIsComplete();
		addField( $13_1$ConstantFormField );
		$13_41$ConstantFormField = new egl.ui.text.TuiField( "$13_41$ConstantFormField", this, null );
		$13_41$ConstantFormField.setPosition(0,13,41);
		$13_41$ConstantFormField.setCurrentValue(0,"|",true);
		$13_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$13_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_41$ConstantFormField.setIsComplete();
		addField( $13_41$ConstantFormField );
		$14_1$ConstantFormField = new egl.ui.text.TuiField( "$14_1$ConstantFormField", this, null );
		$14_1$ConstantFormField.setPosition(0,14,1);
		$14_1$ConstantFormField.setCurrentValue(0,"|",true);
		$14_1$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$14_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_1$ConstantFormField.setIsComplete();
		addField( $14_1$ConstantFormField );
		$14_41$ConstantFormField = new egl.ui.text.TuiField( "$14_41$ConstantFormField", this, null );
		$14_41$ConstantFormField.setPosition(0,14,41);
		$14_41$ConstantFormField.setCurrentValue(0,"|",true);
		$14_41$ConstantFormField.setColor(0,egl.ui.ColorKind.blue);
		$14_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_41$ConstantFormField.setIsComplete();
		addField( $14_41$ConstantFormField );
		setFormGroupClassName("egltui.demogrp.DemoGroup");
		setSize(15,42);
		setIsFloating(false);
		setPosition(6,15);
		signature( "Tegltui/demogrp/PopupForm1;" );
	}
	
}
