// Generated at Tue Jun 12 15:21:45 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.demogrp;

public class DemoGroup$PopupMenu1 extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $3_13$ConstantFormField;
	public egl.ui.text.TuiField $18_13$ConstantFormField;
	public egl.ui.text.TuiField $4_13$ConstantFormField;
	public egl.ui.text.TuiField $4_56$ConstantFormField;
	public egl.ui.text.TuiField $5_13$ConstantFormField;
	public egl.ui.text.TuiField $5_56$ConstantFormField;
	public egl.ui.text.TuiField $6_13$ConstantFormField;
	public egl.ui.text.TuiField $6_56$ConstantFormField;
	public egl.ui.text.TuiField $7_13$ConstantFormField;
	public egl.ui.text.TuiField $7_56$ConstantFormField;
	public egl.ui.text.TuiField $8_13$ConstantFormField;
	public egl.ui.text.TuiField $8_56$ConstantFormField;
	public egl.ui.text.TuiField $9_13$ConstantFormField;
	public egl.ui.text.TuiField $9_56$ConstantFormField;
	public egl.ui.text.TuiField $10_13$ConstantFormField;
	public egl.ui.text.TuiField $10_56$ConstantFormField;
	public egl.ui.text.TuiField $11_13$ConstantFormField;
	public egl.ui.text.TuiField $11_56$ConstantFormField;
	public egl.ui.text.TuiField $12_13$ConstantFormField;
	public egl.ui.text.TuiField $12_56$ConstantFormField;
	public egl.ui.text.TuiField $13_13$ConstantFormField;
	public egl.ui.text.TuiField $13_56$ConstantFormField;
	public egl.ui.text.TuiField $14_13$ConstantFormField;
	public egl.ui.text.TuiField $14_56$ConstantFormField;
	public egl.ui.text.TuiField $15_13$ConstantFormField;
	public egl.ui.text.TuiField $15_56$ConstantFormField;
	public egl.ui.text.TuiField $16_13$ConstantFormField;
	public egl.ui.text.TuiField $16_56$ConstantFormField;
	public egl.ui.text.TuiField $17_13$ConstantFormField;
	public egl.ui.text.TuiField $17_56$ConstantFormField;
	public egl.ui.text.TuiField $4_24$ConstantFormField;
	public egl.ui.text.TuiField $6_15$ConstantFormField;
	public egl.ui.text.TuiField $13_15$ConstantFormField;
	public com.ibm.javart.ref.CharArrayRef VariableFormField1;
	public egl.ui.text.TuiField VariableFormField1$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef VariableFormField2;
	public egl.ui.text.TuiField VariableFormField2$VariableFormField;
	
	public DemoGroup$PopupMenu1( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$3_13$ConstantFormField = new egl.ui.text.TuiField( "$3_13$ConstantFormField", this, null );
		$3_13$ConstantFormField.setPosition(0,3,13);
		$3_13$ConstantFormField.setCurrentValue(0,"--------------------------------------------",true);
		$3_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$3_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_13$ConstantFormField.setIsComplete();
		addField( $3_13$ConstantFormField );
		$18_13$ConstantFormField = new egl.ui.text.TuiField( "$18_13$ConstantFormField", this, null );
		$18_13$ConstantFormField.setPosition(0,18,13);
		$18_13$ConstantFormField.setCurrentValue(0,"--------------------------------------------",true);
		$18_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$18_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$18_13$ConstantFormField.setIsComplete();
		addField( $18_13$ConstantFormField );
		$4_13$ConstantFormField = new egl.ui.text.TuiField( "$4_13$ConstantFormField", this, null );
		$4_13$ConstantFormField.setPosition(0,4,13);
		$4_13$ConstantFormField.setCurrentValue(0,"|",true);
		$4_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$4_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$4_13$ConstantFormField.setIsComplete();
		addField( $4_13$ConstantFormField );
		$4_56$ConstantFormField = new egl.ui.text.TuiField( "$4_56$ConstantFormField", this, null );
		$4_56$ConstantFormField.setPosition(0,4,56);
		$4_56$ConstantFormField.setCurrentValue(0,"|",true);
		$4_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$4_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$4_56$ConstantFormField.setIsComplete();
		addField( $4_56$ConstantFormField );
		$5_13$ConstantFormField = new egl.ui.text.TuiField( "$5_13$ConstantFormField", this, null );
		$5_13$ConstantFormField.setPosition(0,5,13);
		$5_13$ConstantFormField.setCurrentValue(0,"|",true);
		$5_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$5_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_13$ConstantFormField.setIsComplete();
		addField( $5_13$ConstantFormField );
		$5_56$ConstantFormField = new egl.ui.text.TuiField( "$5_56$ConstantFormField", this, null );
		$5_56$ConstantFormField.setPosition(0,5,56);
		$5_56$ConstantFormField.setCurrentValue(0,"|",true);
		$5_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$5_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_56$ConstantFormField.setIsComplete();
		addField( $5_56$ConstantFormField );
		$6_13$ConstantFormField = new egl.ui.text.TuiField( "$6_13$ConstantFormField", this, null );
		$6_13$ConstantFormField.setPosition(0,6,13);
		$6_13$ConstantFormField.setCurrentValue(0,"|",true);
		$6_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$6_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_13$ConstantFormField.setIsComplete();
		addField( $6_13$ConstantFormField );
		$6_56$ConstantFormField = new egl.ui.text.TuiField( "$6_56$ConstantFormField", this, null );
		$6_56$ConstantFormField.setPosition(0,6,56);
		$6_56$ConstantFormField.setCurrentValue(0,"|",true);
		$6_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$6_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_56$ConstantFormField.setIsComplete();
		addField( $6_56$ConstantFormField );
		$7_13$ConstantFormField = new egl.ui.text.TuiField( "$7_13$ConstantFormField", this, null );
		$7_13$ConstantFormField.setPosition(0,7,13);
		$7_13$ConstantFormField.setCurrentValue(0,"|",true);
		$7_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$7_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_13$ConstantFormField.setIsComplete();
		addField( $7_13$ConstantFormField );
		$7_56$ConstantFormField = new egl.ui.text.TuiField( "$7_56$ConstantFormField", this, null );
		$7_56$ConstantFormField.setPosition(0,7,56);
		$7_56$ConstantFormField.setCurrentValue(0,"|",true);
		$7_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$7_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_56$ConstantFormField.setIsComplete();
		addField( $7_56$ConstantFormField );
		$8_13$ConstantFormField = new egl.ui.text.TuiField( "$8_13$ConstantFormField", this, null );
		$8_13$ConstantFormField.setPosition(0,8,13);
		$8_13$ConstantFormField.setCurrentValue(0,"|",true);
		$8_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$8_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_13$ConstantFormField.setIsComplete();
		addField( $8_13$ConstantFormField );
		$8_56$ConstantFormField = new egl.ui.text.TuiField( "$8_56$ConstantFormField", this, null );
		$8_56$ConstantFormField.setPosition(0,8,56);
		$8_56$ConstantFormField.setCurrentValue(0,"|",true);
		$8_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$8_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_56$ConstantFormField.setIsComplete();
		addField( $8_56$ConstantFormField );
		$9_13$ConstantFormField = new egl.ui.text.TuiField( "$9_13$ConstantFormField", this, null );
		$9_13$ConstantFormField.setPosition(0,9,13);
		$9_13$ConstantFormField.setCurrentValue(0,"|",true);
		$9_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$9_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_13$ConstantFormField.setIsComplete();
		addField( $9_13$ConstantFormField );
		$9_56$ConstantFormField = new egl.ui.text.TuiField( "$9_56$ConstantFormField", this, null );
		$9_56$ConstantFormField.setPosition(0,9,56);
		$9_56$ConstantFormField.setCurrentValue(0,"|",true);
		$9_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$9_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_56$ConstantFormField.setIsComplete();
		addField( $9_56$ConstantFormField );
		$10_13$ConstantFormField = new egl.ui.text.TuiField( "$10_13$ConstantFormField", this, null );
		$10_13$ConstantFormField.setPosition(0,10,13);
		$10_13$ConstantFormField.setCurrentValue(0,"|",true);
		$10_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$10_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_13$ConstantFormField.setIsComplete();
		addField( $10_13$ConstantFormField );
		$10_56$ConstantFormField = new egl.ui.text.TuiField( "$10_56$ConstantFormField", this, null );
		$10_56$ConstantFormField.setPosition(0,10,56);
		$10_56$ConstantFormField.setCurrentValue(0,"|",true);
		$10_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$10_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_56$ConstantFormField.setIsComplete();
		addField( $10_56$ConstantFormField );
		$11_13$ConstantFormField = new egl.ui.text.TuiField( "$11_13$ConstantFormField", this, null );
		$11_13$ConstantFormField.setPosition(0,11,13);
		$11_13$ConstantFormField.setCurrentValue(0,"|",true);
		$11_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$11_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_13$ConstantFormField.setIsComplete();
		addField( $11_13$ConstantFormField );
		$11_56$ConstantFormField = new egl.ui.text.TuiField( "$11_56$ConstantFormField", this, null );
		$11_56$ConstantFormField.setPosition(0,11,56);
		$11_56$ConstantFormField.setCurrentValue(0,"|",true);
		$11_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$11_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_56$ConstantFormField.setIsComplete();
		addField( $11_56$ConstantFormField );
		$12_13$ConstantFormField = new egl.ui.text.TuiField( "$12_13$ConstantFormField", this, null );
		$12_13$ConstantFormField.setPosition(0,12,13);
		$12_13$ConstantFormField.setCurrentValue(0,"|",true);
		$12_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$12_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$12_13$ConstantFormField.setIsComplete();
		addField( $12_13$ConstantFormField );
		$12_56$ConstantFormField = new egl.ui.text.TuiField( "$12_56$ConstantFormField", this, null );
		$12_56$ConstantFormField.setPosition(0,12,56);
		$12_56$ConstantFormField.setCurrentValue(0,"|",true);
		$12_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$12_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$12_56$ConstantFormField.setIsComplete();
		addField( $12_56$ConstantFormField );
		$13_13$ConstantFormField = new egl.ui.text.TuiField( "$13_13$ConstantFormField", this, null );
		$13_13$ConstantFormField.setPosition(0,13,13);
		$13_13$ConstantFormField.setCurrentValue(0,"|",true);
		$13_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$13_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_13$ConstantFormField.setIsComplete();
		addField( $13_13$ConstantFormField );
		$13_56$ConstantFormField = new egl.ui.text.TuiField( "$13_56$ConstantFormField", this, null );
		$13_56$ConstantFormField.setPosition(0,13,56);
		$13_56$ConstantFormField.setCurrentValue(0,"|",true);
		$13_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$13_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_56$ConstantFormField.setIsComplete();
		addField( $13_56$ConstantFormField );
		$14_13$ConstantFormField = new egl.ui.text.TuiField( "$14_13$ConstantFormField", this, null );
		$14_13$ConstantFormField.setPosition(0,14,13);
		$14_13$ConstantFormField.setCurrentValue(0,"|",true);
		$14_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$14_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_13$ConstantFormField.setIsComplete();
		addField( $14_13$ConstantFormField );
		$14_56$ConstantFormField = new egl.ui.text.TuiField( "$14_56$ConstantFormField", this, null );
		$14_56$ConstantFormField.setPosition(0,14,56);
		$14_56$ConstantFormField.setCurrentValue(0,"|",true);
		$14_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$14_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_56$ConstantFormField.setIsComplete();
		addField( $14_56$ConstantFormField );
		$15_13$ConstantFormField = new egl.ui.text.TuiField( "$15_13$ConstantFormField", this, null );
		$15_13$ConstantFormField.setPosition(0,15,13);
		$15_13$ConstantFormField.setCurrentValue(0,"|",true);
		$15_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$15_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_13$ConstantFormField.setIsComplete();
		addField( $15_13$ConstantFormField );
		$15_56$ConstantFormField = new egl.ui.text.TuiField( "$15_56$ConstantFormField", this, null );
		$15_56$ConstantFormField.setPosition(0,15,56);
		$15_56$ConstantFormField.setCurrentValue(0,"|",true);
		$15_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$15_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_56$ConstantFormField.setIsComplete();
		addField( $15_56$ConstantFormField );
		$16_13$ConstantFormField = new egl.ui.text.TuiField( "$16_13$ConstantFormField", this, null );
		$16_13$ConstantFormField.setPosition(0,16,13);
		$16_13$ConstantFormField.setCurrentValue(0,"|",true);
		$16_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$16_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_13$ConstantFormField.setIsComplete();
		addField( $16_13$ConstantFormField );
		$16_56$ConstantFormField = new egl.ui.text.TuiField( "$16_56$ConstantFormField", this, null );
		$16_56$ConstantFormField.setPosition(0,16,56);
		$16_56$ConstantFormField.setCurrentValue(0,"|",true);
		$16_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$16_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_56$ConstantFormField.setIsComplete();
		addField( $16_56$ConstantFormField );
		$17_13$ConstantFormField = new egl.ui.text.TuiField( "$17_13$ConstantFormField", this, null );
		$17_13$ConstantFormField.setPosition(0,17,13);
		$17_13$ConstantFormField.setCurrentValue(0,"|",true);
		$17_13$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$17_13$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$17_13$ConstantFormField.setIsComplete();
		addField( $17_13$ConstantFormField );
		$17_56$ConstantFormField = new egl.ui.text.TuiField( "$17_56$ConstantFormField", this, null );
		$17_56$ConstantFormField.setPosition(0,17,56);
		$17_56$ConstantFormField.setCurrentValue(0,"|",true);
		$17_56$ConstantFormField.setColor(0,egl.ui.ColorKind.white);
		$17_56$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$17_56$ConstantFormField.setIsComplete();
		addField( $17_56$ConstantFormField );
		$4_24$ConstantFormField = new egl.ui.text.TuiField( "$4_24$ConstantFormField", this, null );
		$4_24$ConstantFormField.setPosition(0,4,24);
		$4_24$ConstantFormField.setCurrentValue(0,"Title of Popup Menu",true);
		$4_24$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$4_24$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$4_24$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$4_24$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$4_24$ConstantFormField.setIsComplete();
		addField( $4_24$ConstantFormField );
		$6_15$ConstantFormField = new egl.ui.text.TuiField( "$6_15$ConstantFormField", this, null );
		$6_15$ConstantFormField.setLength(35);
		$6_15$ConstantFormField.setPosition(0,6,15);
		$6_15$ConstantFormField.setCurrentValue(0,"Click on an option and Press Enter.",true);
		$6_15$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$6_15$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$6_15$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_15$ConstantFormField.setIsComplete();
		addField( $6_15$ConstantFormField );
		$13_15$ConstantFormField = new egl.ui.text.TuiField( "$13_15$ConstantFormField", this, null );
		$13_15$ConstantFormField.setPosition(0,13,15);
		$13_15$ConstantFormField.setCurrentValue(0,"This is additional help text.",true);
		$13_15$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$13_15$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$13_15$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_15$ConstantFormField.setIsComplete();
		addField( $13_15$ConstantFormField );
		VariableFormField1 = new com.ibm.javart.ref.CharArrayRef( "VariableFormField1", new com.ibm.javart.arrays.CharArray( "VariableFormField1", ezeProgram, 5, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 1, "1C1;" ), "1C1;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "VariableFormField1", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 1, "1C1;" );
			}
		};
		add( VariableFormField1 );
		VariableFormField1$VariableFormField = new egl.ui.text.TuiField( "VariableFormField1$VariableFormField", this, VariableFormField1 );
		VariableFormField1$VariableFormField.setLength(1);
		VariableFormField1$VariableFormField.setPosition(0,8,15);
		VariableFormField1$VariableFormField.setCurrentValue(0,"",true);
		VariableFormField1$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		VariableFormField1$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		VariableFormField1$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		VariableFormField1$VariableFormField.setPosition(1,9,15);
		VariableFormField1$VariableFormField.setCurrentValue(1,"",true);
		VariableFormField1$VariableFormField.setHighlight(1,egl.ui.HighlightKind.underline);
		VariableFormField1$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		VariableFormField1$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.noProtect);
		VariableFormField1$VariableFormField.setPosition(2,10,15);
		VariableFormField1$VariableFormField.setCurrentValue(2,"",true);
		VariableFormField1$VariableFormField.setHighlight(2,egl.ui.HighlightKind.underline);
		VariableFormField1$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		VariableFormField1$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.noProtect);
		VariableFormField1$VariableFormField.setPosition(3,11,15);
		VariableFormField1$VariableFormField.setCurrentValue(3,"",true);
		VariableFormField1$VariableFormField.setHighlight(3,egl.ui.HighlightKind.underline);
		VariableFormField1$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		VariableFormField1$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.noProtect);
		VariableFormField1$VariableFormField.setPosition(4,12,15);
		VariableFormField1$VariableFormField.setCurrentValue(4,"",true);
		VariableFormField1$VariableFormField.setHighlight(4,egl.ui.HighlightKind.underline);
		VariableFormField1$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		VariableFormField1$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.noProtect);
		VariableFormField1$VariableFormField.setJustify(egl.ui.AlignKind.left);
		VariableFormField1$VariableFormField.setIsComplete();
		addField( VariableFormField1$VariableFormField );
		VariableFormField2 = new com.ibm.javart.ref.CharArrayRef( "VariableFormField2", new com.ibm.javart.arrays.CharArray( "VariableFormField2", ezeProgram, 5, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 38, "1C38;" ), "1C38;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "VariableFormField2", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 38, "1C38;" );
			}
		};
		add( VariableFormField2 );
		VariableFormField2$VariableFormField = new egl.ui.text.TuiField( "VariableFormField2$VariableFormField", this, VariableFormField2 );
		VariableFormField2$VariableFormField.setLength(38);
		VariableFormField2$VariableFormField.setPosition(0,8,17);
		VariableFormField2$VariableFormField.setCurrentValue(0,"Option A",false);
		VariableFormField2$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		VariableFormField2$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		VariableFormField2$VariableFormField.setPosition(1,9,17);
		VariableFormField2$VariableFormField.setCurrentValue(1,"Option B",false);
		VariableFormField2$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		VariableFormField2$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.skipProtect);
		VariableFormField2$VariableFormField.setPosition(2,10,17);
		VariableFormField2$VariableFormField.setCurrentValue(2,"Option C",false);
		VariableFormField2$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		VariableFormField2$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.skipProtect);
		VariableFormField2$VariableFormField.setPosition(3,11,17);
		VariableFormField2$VariableFormField.setCurrentValue(3,"Option D",false);
		VariableFormField2$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		VariableFormField2$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.skipProtect);
		VariableFormField2$VariableFormField.setPosition(4,12,17);
		VariableFormField2$VariableFormField.setCurrentValue(4,"Option E",false);
		VariableFormField2$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		VariableFormField2$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.skipProtect);
		VariableFormField2$VariableFormField.setJustify(egl.ui.AlignKind.left);
		VariableFormField2$VariableFormField.setIsComplete();
		addField( VariableFormField2$VariableFormField );
		setFormGroupClassName("egltui.demogrp.DemoGroup");
		setSize(24,80);
		setIsFloating(true);
		setPosition(-1,-1);
		addDeviceSize(24,80);
		signature( "Tegltui/demogrp/PopupMenu1;" );
	}
	
}
