// Generated at Tue Jun 12 15:21:45 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.opt2.custdetail;

public class xyzCD1FormGroup$custDetail extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $1_28$ConstantFormField;
	public egl.ui.text.TuiField $23_3$ConstantFormField;
	public egl.ui.text.TuiField $3_2$ConstantFormField;
	public egl.ui.text.TuiField $3_12$ConstantFormField;
	public egl.ui.text.TuiField $5_2$ConstantFormField;
	public egl.ui.text.TuiField $6_2$ConstantFormField;
	public egl.ui.text.TuiField $7_2$ConstantFormField;
	public egl.ui.text.TuiField $8_2$ConstantFormField;
	public egl.ui.text.TuiField $9_2$ConstantFormField;
	public egl.ui.text.TuiField $10_2$ConstantFormField;
	public egl.ui.text.TuiField $11_2$ConstantFormField;
	public egl.ui.text.TuiField $12_2$ConstantFormField;
	public egl.ui.text.TuiField $13_2$ConstantFormField;
	public egl.ui.text.TuiField $14_2$ConstantFormField;
	public egl.ui.text.TuiField $15_2$ConstantFormField;
	public egl.ui.text.TuiField $16_2$ConstantFormField;
	public com.ibm.javart.CharValue formMSG;
	public egl.ui.text.TuiField formMSG$VariableFormField;
	public com.ibm.javart.CharValue screenName;
	public egl.ui.text.TuiField screenName$VariableFormField;
	public com.ibm.javart.CharValue screenDate;
	public egl.ui.text.TuiField screenDate$VariableFormField;
	public com.ibm.javart.CharValue Action;
	public egl.ui.text.TuiField Action$VariableFormField;
	public com.ibm.javart.IntValue CustomerId;
	public egl.ui.text.TuiField CustomerId$VariableFormField;
	public com.ibm.javart.CharValue FirstName;
	public egl.ui.text.TuiField FirstName$VariableFormField;
	public com.ibm.javart.CharValue LastName;
	public egl.ui.text.TuiField LastName$VariableFormField;
	public com.ibm.javart.CharValue Password;
	public egl.ui.text.TuiField Password$VariableFormField;
	public com.ibm.javart.CharValue Phone;
	public egl.ui.text.TuiField Phone$VariableFormField;
	public com.ibm.javart.CharValue EmailAddress;
	public egl.ui.text.TuiField EmailAddress$VariableFormField;
	public com.ibm.javart.CharValue Street;
	public egl.ui.text.TuiField Street$VariableFormField;
	public com.ibm.javart.CharValue Apartment;
	public egl.ui.text.TuiField Apartment$VariableFormField;
	public com.ibm.javart.CharValue City;
	public egl.ui.text.TuiField City$VariableFormField;
	public com.ibm.javart.CharValue State;
	public egl.ui.text.TuiField State$VariableFormField;
	public com.ibm.javart.CharValue Postalcode;
	public egl.ui.text.TuiField Postalcode$VariableFormField;
	public com.ibm.javart.CharValue Directions;
	public egl.ui.text.TuiField Directions$VariableFormField;
	
	public xyzCD1FormGroup$custDetail( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$1_28$ConstantFormField = new egl.ui.text.TuiField( "$1_28$ConstantFormField", this, null );
		$1_28$ConstantFormField.setLength(20);
		$1_28$ConstantFormField.setPosition(0,1,28);
		$1_28$ConstantFormField.setCurrentValue(0,"Customer Detail",true);
		$1_28$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$1_28$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$1_28$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$1_28$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$1_28$ConstantFormField.setIsComplete();
		addField( $1_28$ConstantFormField );
		$23_3$ConstantFormField = new egl.ui.text.TuiField( "$23_3$ConstantFormField", this, null );
		$23_3$ConstantFormField.setLength(75);
		$23_3$ConstantFormField.setPosition(0,23,3);
		$23_3$ConstantFormField.setCurrentValue(0,"F2=Menu;  F3=Exit;  F4=List;  Enter=Process Action request",true);
		$23_3$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$23_3$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$23_3$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$23_3$ConstantFormField.setIsComplete();
		addField( $23_3$ConstantFormField );
		$3_2$ConstantFormField = new egl.ui.text.TuiField( "$3_2$ConstantFormField", this, null );
		$3_2$ConstantFormField.setPosition(0,3,2);
		$3_2$ConstantFormField.setCurrentValue(0,"Action:",true);
		$3_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$3_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$3_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_2$ConstantFormField.setIsComplete();
		addField( $3_2$ConstantFormField );
		$3_12$ConstantFormField = new egl.ui.text.TuiField( "$3_12$ConstantFormField", this, null );
		$3_12$ConstantFormField.setPosition(0,3,12);
		$3_12$ConstantFormField.setCurrentValue(0,"(I=insert, S=select, U=update, D=delete",true);
		$3_12$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$3_12$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$3_12$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_12$ConstantFormField.setIsComplete();
		addField( $3_12$ConstantFormField );
		$5_2$ConstantFormField = new egl.ui.text.TuiField( "$5_2$ConstantFormField", this, null );
		$5_2$ConstantFormField.setPosition(0,5,2);
		$5_2$ConstantFormField.setCurrentValue(0,"Customer ID",true);
		$5_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_2$ConstantFormField.setIsComplete();
		addField( $5_2$ConstantFormField );
		$6_2$ConstantFormField = new egl.ui.text.TuiField( "$6_2$ConstantFormField", this, null );
		$6_2$ConstantFormField.setPosition(0,6,2);
		$6_2$ConstantFormField.setCurrentValue(0,"First Name",true);
		$6_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$6_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$6_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_2$ConstantFormField.setIsComplete();
		addField( $6_2$ConstantFormField );
		$7_2$ConstantFormField = new egl.ui.text.TuiField( "$7_2$ConstantFormField", this, null );
		$7_2$ConstantFormField.setPosition(0,7,2);
		$7_2$ConstantFormField.setCurrentValue(0,"Last Name",true);
		$7_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$7_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$7_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_2$ConstantFormField.setIsComplete();
		addField( $7_2$ConstantFormField );
		$8_2$ConstantFormField = new egl.ui.text.TuiField( "$8_2$ConstantFormField", this, null );
		$8_2$ConstantFormField.setPosition(0,8,2);
		$8_2$ConstantFormField.setCurrentValue(0,"Password",true);
		$8_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$8_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$8_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_2$ConstantFormField.setIsComplete();
		addField( $8_2$ConstantFormField );
		$9_2$ConstantFormField = new egl.ui.text.TuiField( "$9_2$ConstantFormField", this, null );
		$9_2$ConstantFormField.setPosition(0,9,2);
		$9_2$ConstantFormField.setCurrentValue(0,"Phone",true);
		$9_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$9_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$9_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_2$ConstantFormField.setIsComplete();
		addField( $9_2$ConstantFormField );
		$10_2$ConstantFormField = new egl.ui.text.TuiField( "$10_2$ConstantFormField", this, null );
		$10_2$ConstantFormField.setPosition(0,10,2);
		$10_2$ConstantFormField.setCurrentValue(0,"E-mail Address",true);
		$10_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$10_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$10_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_2$ConstantFormField.setIsComplete();
		addField( $10_2$ConstantFormField );
		$11_2$ConstantFormField = new egl.ui.text.TuiField( "$11_2$ConstantFormField", this, null );
		$11_2$ConstantFormField.setPosition(0,11,2);
		$11_2$ConstantFormField.setCurrentValue(0,"Street",true);
		$11_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$11_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$11_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_2$ConstantFormField.setIsComplete();
		addField( $11_2$ConstantFormField );
		$12_2$ConstantFormField = new egl.ui.text.TuiField( "$12_2$ConstantFormField", this, null );
		$12_2$ConstantFormField.setPosition(0,12,2);
		$12_2$ConstantFormField.setCurrentValue(0,"Apartment",true);
		$12_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$12_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$12_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$12_2$ConstantFormField.setIsComplete();
		addField( $12_2$ConstantFormField );
		$13_2$ConstantFormField = new egl.ui.text.TuiField( "$13_2$ConstantFormField", this, null );
		$13_2$ConstantFormField.setPosition(0,13,2);
		$13_2$ConstantFormField.setCurrentValue(0,"City",true);
		$13_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$13_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$13_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_2$ConstantFormField.setIsComplete();
		addField( $13_2$ConstantFormField );
		$14_2$ConstantFormField = new egl.ui.text.TuiField( "$14_2$ConstantFormField", this, null );
		$14_2$ConstantFormField.setPosition(0,14,2);
		$14_2$ConstantFormField.setCurrentValue(0,"State",true);
		$14_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$14_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$14_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_2$ConstantFormField.setIsComplete();
		addField( $14_2$ConstantFormField );
		$15_2$ConstantFormField = new egl.ui.text.TuiField( "$15_2$ConstantFormField", this, null );
		$15_2$ConstantFormField.setPosition(0,15,2);
		$15_2$ConstantFormField.setCurrentValue(0,"Postalcode",true);
		$15_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$15_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$15_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_2$ConstantFormField.setIsComplete();
		addField( $15_2$ConstantFormField );
		$16_2$ConstantFormField = new egl.ui.text.TuiField( "$16_2$ConstantFormField", this, null );
		$16_2$ConstantFormField.setPosition(0,16,2);
		$16_2$ConstantFormField.setCurrentValue(0,"Directions",true);
		$16_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$16_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$16_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_2$ConstantFormField.setIsComplete();
		addField( $16_2$ConstantFormField );
		formMSG = new com.ibm.javart.CharItem( "formMSG", com.ibm.javart.Value.SQL_NOT_NULLABLE, 76, true, "C76;" );
		add( formMSG );
		formMSG$VariableFormField = new egl.ui.text.TuiField( "formMSG$VariableFormField", this, formMSG );
		formMSG$VariableFormField.setLength(76);
		formMSG$VariableFormField.setPosition(0,22,3);
		formMSG$VariableFormField.setCurrentValue(0,"",true);
		formMSG$VariableFormField.setHighlight(0,egl.ui.HighlightKind.noHighlight);
		formMSG$VariableFormField.setColor(0,egl.ui.ColorKind.red);
		formMSG$VariableFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		formMSG$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		formMSG$VariableFormField.setJustify(egl.ui.AlignKind.left);
		formMSG$VariableFormField.setIsComplete();
		addField( formMSG$VariableFormField );
		screenName = new com.ibm.javart.CharItem( "screenName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 9, true, "C9;" );
		add( screenName );
		screenName$VariableFormField = new egl.ui.text.TuiField( "screenName$VariableFormField", this, screenName );
		screenName$VariableFormField.setLength(9);
		screenName$VariableFormField.setPosition(0,1,1);
		screenName$VariableFormField.setCurrentValue(0,"",true);
		screenName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenName$VariableFormField.setIsComplete();
		addField( screenName$VariableFormField );
		screenDate = new com.ibm.javart.CharItem( "screenDate", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( screenDate );
		screenDate$VariableFormField = new egl.ui.text.TuiField( "screenDate$VariableFormField", this, screenDate );
		screenDate$VariableFormField.setLength(10);
		screenDate$VariableFormField.setPosition(0,1,62);
		screenDate$VariableFormField.setCurrentValue(0,"",true);
		screenDate$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenDate$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenDate$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenDate$VariableFormField.setIsComplete();
		addField( screenDate$VariableFormField );
		Action = new com.ibm.javart.CharItem( "Action", com.ibm.javart.Value.SQL_NOT_NULLABLE, 1, true, "C1;" );
		add( Action );
		Action$VariableFormField = new egl.ui.text.TuiField( "Action$VariableFormField", this, Action );
		Action$VariableFormField.setLength(1);
		Action$VariableFormField.setPosition(0,3,10);
		Action$VariableFormField.setCurrentValue(0,"",true);
		Action$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Action$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Action$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Action$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Action$VariableFormField.setUpperCase(true);
		Action$VariableFormField.setIsComplete();
		addField( Action$VariableFormField );
		CustomerId = new com.ibm.javart.IntItem( "CustomerId", com.ibm.javart.Value.SQL_NOT_NULLABLE, com.ibm.javart.Constants.SIGNATURE_INT );
		add( CustomerId );
		CustomerId$VariableFormField = new egl.ui.text.TuiField( "CustomerId$VariableFormField", this, CustomerId );
		CustomerId$VariableFormField.setLength(9);
		CustomerId$VariableFormField.setPosition(0,5,18);
		CustomerId$VariableFormField.setCurrentValue(0,"",true);
		CustomerId$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		CustomerId$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		CustomerId$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		CustomerId$VariableFormField.setConversionDescriptor(-9);
		CustomerId$VariableFormField.setJustify(egl.ui.AlignKind.right);
		CustomerId$VariableFormField.setIsComplete();
		addField( CustomerId$VariableFormField );
		FirstName = new com.ibm.javart.CharItem( "FirstName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 30, true, "C30;" );
		add( FirstName );
		FirstName$VariableFormField = new egl.ui.text.TuiField( "FirstName$VariableFormField", this, FirstName );
		FirstName$VariableFormField.setLength(30);
		FirstName$VariableFormField.setPosition(0,6,18);
		FirstName$VariableFormField.setCurrentValue(0,"",true);
		FirstName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		FirstName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		FirstName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		FirstName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		FirstName$VariableFormField.setIsComplete();
		addField( FirstName$VariableFormField );
		LastName = new com.ibm.javart.CharItem( "LastName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 30, true, "C30;" );
		add( LastName );
		LastName$VariableFormField = new egl.ui.text.TuiField( "LastName$VariableFormField", this, LastName );
		LastName$VariableFormField.setLength(30);
		LastName$VariableFormField.setPosition(0,7,18);
		LastName$VariableFormField.setCurrentValue(0,"",true);
		LastName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		LastName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		LastName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		LastName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		LastName$VariableFormField.setIsComplete();
		addField( LastName$VariableFormField );
		Password = new com.ibm.javart.CharItem( "Password", com.ibm.javart.Value.SQL_NOT_NULLABLE, 8, true, "C8;" );
		add( Password );
		Password$VariableFormField = new egl.ui.text.TuiField( "Password$VariableFormField", this, Password );
		Password$VariableFormField.setLength(8);
		Password$VariableFormField.setPosition(0,8,18);
		Password$VariableFormField.setCurrentValue(0,"",true);
		Password$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Password$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Password$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Password$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Password$VariableFormField.setIsComplete();
		addField( Password$VariableFormField );
		Phone = new com.ibm.javart.CharItem( "Phone", com.ibm.javart.Value.SQL_NOT_NULLABLE, 14, true, "C14;" );
		add( Phone );
		Phone$VariableFormField = new egl.ui.text.TuiField( "Phone$VariableFormField", this, Phone );
		Phone$VariableFormField.setLength(14);
		Phone$VariableFormField.setPosition(0,9,18);
		Phone$VariableFormField.setCurrentValue(0,"",true);
		Phone$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Phone$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Phone$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Phone$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Phone$VariableFormField.setIsComplete();
		addField( Phone$VariableFormField );
		EmailAddress = new com.ibm.javart.CharItem( "EmailAddress", com.ibm.javart.Value.SQL_NOT_NULLABLE, 50, true, "C50;" );
		add( EmailAddress );
		EmailAddress$VariableFormField = new egl.ui.text.TuiField( "EmailAddress$VariableFormField", this, EmailAddress );
		EmailAddress$VariableFormField.setLength(50);
		EmailAddress$VariableFormField.setPosition(0,10,18);
		EmailAddress$VariableFormField.setCurrentValue(0,"",true);
		EmailAddress$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		EmailAddress$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		EmailAddress$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		EmailAddress$VariableFormField.setJustify(egl.ui.AlignKind.left);
		EmailAddress$VariableFormField.setIsComplete();
		addField( EmailAddress$VariableFormField );
		Street = new com.ibm.javart.CharItem( "Street", com.ibm.javart.Value.SQL_NOT_NULLABLE, 30, true, "C30;" );
		add( Street );
		Street$VariableFormField = new egl.ui.text.TuiField( "Street$VariableFormField", this, Street );
		Street$VariableFormField.setLength(30);
		Street$VariableFormField.setPosition(0,11,18);
		Street$VariableFormField.setCurrentValue(0,"",true);
		Street$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Street$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Street$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Street$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Street$VariableFormField.setIsComplete();
		addField( Street$VariableFormField );
		Apartment = new com.ibm.javart.CharItem( "Apartment", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( Apartment );
		Apartment$VariableFormField = new egl.ui.text.TuiField( "Apartment$VariableFormField", this, Apartment );
		Apartment$VariableFormField.setLength(10);
		Apartment$VariableFormField.setPosition(0,12,18);
		Apartment$VariableFormField.setCurrentValue(0,"",true);
		Apartment$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Apartment$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Apartment$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Apartment$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Apartment$VariableFormField.setIsComplete();
		addField( Apartment$VariableFormField );
		City = new com.ibm.javart.CharItem( "City", com.ibm.javart.Value.SQL_NOT_NULLABLE, 30, true, "C30;" );
		add( City );
		City$VariableFormField = new egl.ui.text.TuiField( "City$VariableFormField", this, City );
		City$VariableFormField.setLength(30);
		City$VariableFormField.setPosition(0,13,18);
		City$VariableFormField.setCurrentValue(0,"",true);
		City$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		City$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		City$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		City$VariableFormField.setJustify(egl.ui.AlignKind.left);
		City$VariableFormField.setIsComplete();
		addField( City$VariableFormField );
		State = new com.ibm.javart.CharItem( "State", com.ibm.javart.Value.SQL_NOT_NULLABLE, 2, true, "C2;" );
		add( State );
		State$VariableFormField = new egl.ui.text.TuiField( "State$VariableFormField", this, State );
		State$VariableFormField.setLength(2);
		State$VariableFormField.setPosition(0,14,18);
		State$VariableFormField.setCurrentValue(0,"",true);
		State$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		State$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		State$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		State$VariableFormField.setJustify(egl.ui.AlignKind.left);
		State$VariableFormField.setIsComplete();
		addField( State$VariableFormField );
		Postalcode = new com.ibm.javart.CharItem( "Postalcode", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( Postalcode );
		Postalcode$VariableFormField = new egl.ui.text.TuiField( "Postalcode$VariableFormField", this, Postalcode );
		Postalcode$VariableFormField.setLength(10);
		Postalcode$VariableFormField.setPosition(0,15,18);
		Postalcode$VariableFormField.setCurrentValue(0,"",true);
		Postalcode$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Postalcode$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Postalcode$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Postalcode$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Postalcode$VariableFormField.setIsComplete();
		addField( Postalcode$VariableFormField );
		Directions = new com.ibm.javart.CharItem( "Directions", com.ibm.javart.Value.SQL_NOT_NULLABLE, 255, true, "C255;" );
		add( Directions );
		Directions$VariableFormField = new egl.ui.text.TuiField( "Directions$VariableFormField", this, Directions );
		Directions$VariableFormField.setLength(255);
		Directions$VariableFormField.setPosition(0,16,18);
		Directions$VariableFormField.setCurrentValue(0,"",true);
		Directions$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		Directions$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		Directions$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		Directions$VariableFormField.setJustify(egl.ui.AlignKind.left);
		Directions$VariableFormField.setIsComplete();
		addField( Directions$VariableFormField );
		setFormGroupClassName("egltui.opt2.custdetail.xyzCD1FormGroup");
		setSize(24,80);
		setIsFloating(false);
		setPosition(1,1);
		setMessageField(formMSG$VariableFormField);
		addDeviceSize(24,80);
		signature( "Tegltui/opt2/custdetail/custDetail;" );
	}
	
}
