// Generated at Mon Jun 11 21:44:44 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.opt1.custlist;

public class xyzCL1FormGroup$custList extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $5_2$ConstantFormField;
	public egl.ui.text.TuiField $5_19$ConstantFormField;
	public egl.ui.text.TuiField $5_41$ConstantFormField;
	public egl.ui.text.TuiField $5_61$ConstantFormField;
	public egl.ui.text.TuiField $1_28$ConstantFormField;
	public egl.ui.text.TuiField $23_3$ConstantFormField;
	public egl.ui.text.TuiField $3_2$ConstantFormField;
	public com.ibm.javart.CharValue formMSG;
	public egl.ui.text.TuiField formMSG$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef firstName;
	public egl.ui.text.TuiField firstName$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef lastName;
	public egl.ui.text.TuiField lastName$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef city;
	public egl.ui.text.TuiField city$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef state;
	public egl.ui.text.TuiField state$VariableFormField;
	public com.ibm.javart.CharValue screenName;
	public egl.ui.text.TuiField screenName$VariableFormField;
	public com.ibm.javart.CharValue screenDate;
	public egl.ui.text.TuiField screenDate$VariableFormField;
	public com.ibm.javart.CharValue StartName;
	public egl.ui.text.TuiField StartName$VariableFormField;
	
	public xyzCL1FormGroup$custList( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$5_2$ConstantFormField = new egl.ui.text.TuiField( "$5_2$ConstantFormField", this, null );
		$5_2$ConstantFormField.setLength(15);
		$5_2$ConstantFormField.setPosition(0,5,2);
		$5_2$ConstantFormField.setCurrentValue(0,"First Name",true);
		$5_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_2$ConstantFormField.setIsComplete();
		addField( $5_2$ConstantFormField );
		$5_19$ConstantFormField = new egl.ui.text.TuiField( "$5_19$ConstantFormField", this, null );
		$5_19$ConstantFormField.setLength(20);
		$5_19$ConstantFormField.setPosition(0,5,19);
		$5_19$ConstantFormField.setCurrentValue(0,"Last Name",true);
		$5_19$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_19$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_19$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_19$ConstantFormField.setIsComplete();
		addField( $5_19$ConstantFormField );
		$5_41$ConstantFormField = new egl.ui.text.TuiField( "$5_41$ConstantFormField", this, null );
		$5_41$ConstantFormField.setLength(15);
		$5_41$ConstantFormField.setPosition(0,5,41);
		$5_41$ConstantFormField.setCurrentValue(0,"City",true);
		$5_41$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_41$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_41$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_41$ConstantFormField.setIsComplete();
		addField( $5_41$ConstantFormField );
		$5_61$ConstantFormField = new egl.ui.text.TuiField( "$5_61$ConstantFormField", this, null );
		$5_61$ConstantFormField.setLength(5);
		$5_61$ConstantFormField.setPosition(0,5,61);
		$5_61$ConstantFormField.setCurrentValue(0,"State",true);
		$5_61$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_61$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_61$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_61$ConstantFormField.setIsComplete();
		addField( $5_61$ConstantFormField );
		$1_28$ConstantFormField = new egl.ui.text.TuiField( "$1_28$ConstantFormField", this, null );
		$1_28$ConstantFormField.setLength(20);
		$1_28$ConstantFormField.setPosition(0,1,28);
		$1_28$ConstantFormField.setCurrentValue(0,"List of Customers",true);
		$1_28$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$1_28$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$1_28$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$1_28$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$1_28$ConstantFormField.setIsComplete();
		addField( $1_28$ConstantFormField );
		$23_3$ConstantFormField = new egl.ui.text.TuiField( "$23_3$ConstantFormField", this, null );
		$23_3$ConstantFormField.setLength(75);
		$23_3$ConstantFormField.setPosition(0,23,3);
		$23_3$ConstantFormField.setCurrentValue(0,"F2=Menu;  F3=Exit;  F5=Detail;  Enter=Rebuild List based on Start Field",true);
		$23_3$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$23_3$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$23_3$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$23_3$ConstantFormField.setIsComplete();
		addField( $23_3$ConstantFormField );
		$3_2$ConstantFormField = new egl.ui.text.TuiField( "$3_2$ConstantFormField", this, null );
		$3_2$ConstantFormField.setPosition(0,3,2);
		$3_2$ConstantFormField.setCurrentValue(0,"Start from Last Name:",true);
		$3_2$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$3_2$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$3_2$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_2$ConstantFormField.setIsComplete();
		addField( $3_2$ConstantFormField );
		formMSG = new com.ibm.javart.CharItem( "formMSG", com.ibm.javart.Value.SQL_NOT_NULLABLE, 76, true, "C76;" );
		add( formMSG );
		formMSG$VariableFormField = new egl.ui.text.TuiField( "formMSG$VariableFormField", this, formMSG );
		formMSG$VariableFormField.setLength(76);
		formMSG$VariableFormField.setPosition(0,22,3);
		formMSG$VariableFormField.setCurrentValue(0,"",true);
		formMSG$VariableFormField.setHighlight(0,egl.ui.HighlightKind.noHighlight);
		formMSG$VariableFormField.setColor(0,egl.ui.ColorKind.red);
		formMSG$VariableFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		formMSG$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		formMSG$VariableFormField.setJustify(egl.ui.AlignKind.left);
		formMSG$VariableFormField.setIsComplete();
		addField( formMSG$VariableFormField );
		firstName = new com.ibm.javart.ref.CharArrayRef( "firstName", new com.ibm.javart.arrays.CharArray( "firstName", ezeProgram, 15, 15, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 15, "1C15;" ), "1C15;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "firstName", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 15, "1C15;" );
			}
		};
		add( firstName );
		firstName$VariableFormField = new egl.ui.text.TuiField( "firstName$VariableFormField", this, firstName );
		firstName$VariableFormField.setLength(15);
		firstName$VariableFormField.setPosition(0,6,2);
		firstName$VariableFormField.setCurrentValue(0,"",true);
		firstName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(1,7,2);
		firstName$VariableFormField.setCurrentValue(1,"",true);
		firstName$VariableFormField.setHighlight(1,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(2,8,2);
		firstName$VariableFormField.setCurrentValue(2,"",true);
		firstName$VariableFormField.setHighlight(2,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(3,9,2);
		firstName$VariableFormField.setCurrentValue(3,"",true);
		firstName$VariableFormField.setHighlight(3,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(4,10,2);
		firstName$VariableFormField.setCurrentValue(4,"",true);
		firstName$VariableFormField.setHighlight(4,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(5,11,2);
		firstName$VariableFormField.setCurrentValue(5,"",true);
		firstName$VariableFormField.setHighlight(5,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(5,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(5,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(6,12,2);
		firstName$VariableFormField.setCurrentValue(6,"",true);
		firstName$VariableFormField.setHighlight(6,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(6,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(6,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(7,13,2);
		firstName$VariableFormField.setCurrentValue(7,"",true);
		firstName$VariableFormField.setHighlight(7,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(7,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(7,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(8,14,2);
		firstName$VariableFormField.setCurrentValue(8,"",true);
		firstName$VariableFormField.setHighlight(8,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(8,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(8,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(9,15,2);
		firstName$VariableFormField.setCurrentValue(9,"",true);
		firstName$VariableFormField.setHighlight(9,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(9,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(9,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(10,16,2);
		firstName$VariableFormField.setCurrentValue(10,"",true);
		firstName$VariableFormField.setHighlight(10,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(10,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(10,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(11,17,2);
		firstName$VariableFormField.setCurrentValue(11,"",true);
		firstName$VariableFormField.setHighlight(11,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(11,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(11,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(12,18,2);
		firstName$VariableFormField.setCurrentValue(12,"",true);
		firstName$VariableFormField.setHighlight(12,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(12,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(12,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(13,19,2);
		firstName$VariableFormField.setCurrentValue(13,"",true);
		firstName$VariableFormField.setHighlight(13,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(13,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(13,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setPosition(14,20,2);
		firstName$VariableFormField.setCurrentValue(14,"",true);
		firstName$VariableFormField.setHighlight(14,egl.ui.HighlightKind.underline);
		firstName$VariableFormField.setColor(14,egl.ui.ColorKind.green);
		firstName$VariableFormField.setProtect(14,egl.ui.text.ProtectKind.noProtect);
		firstName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		firstName$VariableFormField.setIsComplete();
		addField( firstName$VariableFormField );
		lastName = new com.ibm.javart.ref.CharArrayRef( "lastName", new com.ibm.javart.arrays.CharArray( "lastName", ezeProgram, 15, 15, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 20, "1C20;" ), "1C20;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "lastName", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 20, "1C20;" );
			}
		};
		add( lastName );
		lastName$VariableFormField = new egl.ui.text.TuiField( "lastName$VariableFormField", this, lastName );
		lastName$VariableFormField.setLength(20);
		lastName$VariableFormField.setPosition(0,6,19);
		lastName$VariableFormField.setCurrentValue(0,"",true);
		lastName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(1,7,19);
		lastName$VariableFormField.setCurrentValue(1,"",true);
		lastName$VariableFormField.setHighlight(1,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(2,8,19);
		lastName$VariableFormField.setCurrentValue(2,"",true);
		lastName$VariableFormField.setHighlight(2,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(3,9,19);
		lastName$VariableFormField.setCurrentValue(3,"",true);
		lastName$VariableFormField.setHighlight(3,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(4,10,19);
		lastName$VariableFormField.setCurrentValue(4,"",true);
		lastName$VariableFormField.setHighlight(4,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(5,11,19);
		lastName$VariableFormField.setCurrentValue(5,"",true);
		lastName$VariableFormField.setHighlight(5,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(5,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(5,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(6,12,19);
		lastName$VariableFormField.setCurrentValue(6,"",true);
		lastName$VariableFormField.setHighlight(6,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(6,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(6,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(7,13,19);
		lastName$VariableFormField.setCurrentValue(7,"",true);
		lastName$VariableFormField.setHighlight(7,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(7,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(7,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(8,14,19);
		lastName$VariableFormField.setCurrentValue(8,"",true);
		lastName$VariableFormField.setHighlight(8,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(8,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(8,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(9,15,19);
		lastName$VariableFormField.setCurrentValue(9,"",true);
		lastName$VariableFormField.setHighlight(9,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(9,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(9,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(10,16,19);
		lastName$VariableFormField.setCurrentValue(10,"",true);
		lastName$VariableFormField.setHighlight(10,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(10,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(10,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(11,17,19);
		lastName$VariableFormField.setCurrentValue(11,"",true);
		lastName$VariableFormField.setHighlight(11,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(11,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(11,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(12,18,19);
		lastName$VariableFormField.setCurrentValue(12,"",true);
		lastName$VariableFormField.setHighlight(12,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(12,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(12,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(13,19,19);
		lastName$VariableFormField.setCurrentValue(13,"",true);
		lastName$VariableFormField.setHighlight(13,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(13,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(13,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setPosition(14,20,19);
		lastName$VariableFormField.setCurrentValue(14,"",true);
		lastName$VariableFormField.setHighlight(14,egl.ui.HighlightKind.underline);
		lastName$VariableFormField.setColor(14,egl.ui.ColorKind.green);
		lastName$VariableFormField.setProtect(14,egl.ui.text.ProtectKind.noProtect);
		lastName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		lastName$VariableFormField.setIsComplete();
		addField( lastName$VariableFormField );
		city = new com.ibm.javart.ref.CharArrayRef( "city", new com.ibm.javart.arrays.CharArray( "city", ezeProgram, 15, 15, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 20, "1C20;" ), "1C20;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "city", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 20, "1C20;" );
			}
		};
		add( city );
		city$VariableFormField = new egl.ui.text.TuiField( "city$VariableFormField", this, city );
		city$VariableFormField.setLength(20);
		city$VariableFormField.setPosition(0,6,41);
		city$VariableFormField.setCurrentValue(0,"",true);
		city$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(1,7,41);
		city$VariableFormField.setCurrentValue(1,"",true);
		city$VariableFormField.setHighlight(1,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(2,8,41);
		city$VariableFormField.setCurrentValue(2,"",true);
		city$VariableFormField.setHighlight(2,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(3,9,41);
		city$VariableFormField.setCurrentValue(3,"",true);
		city$VariableFormField.setHighlight(3,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(4,10,41);
		city$VariableFormField.setCurrentValue(4,"",true);
		city$VariableFormField.setHighlight(4,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(5,11,41);
		city$VariableFormField.setCurrentValue(5,"",true);
		city$VariableFormField.setHighlight(5,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(5,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(5,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(6,12,41);
		city$VariableFormField.setCurrentValue(6,"",true);
		city$VariableFormField.setHighlight(6,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(6,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(6,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(7,13,41);
		city$VariableFormField.setCurrentValue(7,"",true);
		city$VariableFormField.setHighlight(7,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(7,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(7,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(8,14,41);
		city$VariableFormField.setCurrentValue(8,"",true);
		city$VariableFormField.setHighlight(8,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(8,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(8,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(9,15,41);
		city$VariableFormField.setCurrentValue(9,"",true);
		city$VariableFormField.setHighlight(9,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(9,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(9,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(10,16,41);
		city$VariableFormField.setCurrentValue(10,"",true);
		city$VariableFormField.setHighlight(10,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(10,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(10,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(11,17,41);
		city$VariableFormField.setCurrentValue(11,"",true);
		city$VariableFormField.setHighlight(11,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(11,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(11,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(12,18,41);
		city$VariableFormField.setCurrentValue(12,"",true);
		city$VariableFormField.setHighlight(12,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(12,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(12,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(13,19,41);
		city$VariableFormField.setCurrentValue(13,"",true);
		city$VariableFormField.setHighlight(13,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(13,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(13,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setPosition(14,20,41);
		city$VariableFormField.setCurrentValue(14,"",true);
		city$VariableFormField.setHighlight(14,egl.ui.HighlightKind.underline);
		city$VariableFormField.setColor(14,egl.ui.ColorKind.green);
		city$VariableFormField.setProtect(14,egl.ui.text.ProtectKind.noProtect);
		city$VariableFormField.setJustify(egl.ui.AlignKind.left);
		city$VariableFormField.setIsComplete();
		addField( city$VariableFormField );
		state = new com.ibm.javart.ref.CharArrayRef( "state", new com.ibm.javart.arrays.CharArray( "state", ezeProgram, 15, 15, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 2, "1C2;" ), "1C2;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "state", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 2, "1C2;" );
			}
		};
		add( state );
		state$VariableFormField = new egl.ui.text.TuiField( "state$VariableFormField", this, state );
		state$VariableFormField.setLength(2);
		state$VariableFormField.setPosition(0,6,63);
		state$VariableFormField.setCurrentValue(0,"",true);
		state$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(1,7,63);
		state$VariableFormField.setCurrentValue(1,"",true);
		state$VariableFormField.setHighlight(1,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(2,8,63);
		state$VariableFormField.setCurrentValue(2,"",true);
		state$VariableFormField.setHighlight(2,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(3,9,63);
		state$VariableFormField.setCurrentValue(3,"",true);
		state$VariableFormField.setHighlight(3,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(4,10,63);
		state$VariableFormField.setCurrentValue(4,"",true);
		state$VariableFormField.setHighlight(4,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(5,11,63);
		state$VariableFormField.setCurrentValue(5,"",true);
		state$VariableFormField.setHighlight(5,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(5,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(5,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(6,12,63);
		state$VariableFormField.setCurrentValue(6,"",true);
		state$VariableFormField.setHighlight(6,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(6,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(6,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(7,13,63);
		state$VariableFormField.setCurrentValue(7,"",true);
		state$VariableFormField.setHighlight(7,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(7,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(7,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(8,14,63);
		state$VariableFormField.setCurrentValue(8,"",true);
		state$VariableFormField.setHighlight(8,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(8,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(8,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(9,15,63);
		state$VariableFormField.setCurrentValue(9,"",true);
		state$VariableFormField.setHighlight(9,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(9,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(9,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(10,16,63);
		state$VariableFormField.setCurrentValue(10,"",true);
		state$VariableFormField.setHighlight(10,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(10,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(10,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(11,17,63);
		state$VariableFormField.setCurrentValue(11,"",true);
		state$VariableFormField.setHighlight(11,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(11,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(11,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(12,18,63);
		state$VariableFormField.setCurrentValue(12,"",true);
		state$VariableFormField.setHighlight(12,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(12,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(12,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(13,19,63);
		state$VariableFormField.setCurrentValue(13,"",true);
		state$VariableFormField.setHighlight(13,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(13,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(13,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setPosition(14,20,63);
		state$VariableFormField.setCurrentValue(14,"",true);
		state$VariableFormField.setHighlight(14,egl.ui.HighlightKind.underline);
		state$VariableFormField.setColor(14,egl.ui.ColorKind.green);
		state$VariableFormField.setProtect(14,egl.ui.text.ProtectKind.noProtect);
		state$VariableFormField.setJustify(egl.ui.AlignKind.left);
		state$VariableFormField.setIsComplete();
		addField( state$VariableFormField );
		screenName = new com.ibm.javart.CharItem( "screenName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 9, true, "C9;" );
		add( screenName );
		screenName$VariableFormField = new egl.ui.text.TuiField( "screenName$VariableFormField", this, screenName );
		screenName$VariableFormField.setLength(9);
		screenName$VariableFormField.setPosition(0,1,1);
		screenName$VariableFormField.setCurrentValue(0,"",true);
		screenName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenName$VariableFormField.setIsComplete();
		addField( screenName$VariableFormField );
		screenDate = new com.ibm.javart.CharItem( "screenDate", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( screenDate );
		screenDate$VariableFormField = new egl.ui.text.TuiField( "screenDate$VariableFormField", this, screenDate );
		screenDate$VariableFormField.setLength(10);
		screenDate$VariableFormField.setPosition(0,1,62);
		screenDate$VariableFormField.setCurrentValue(0,"",true);
		screenDate$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenDate$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenDate$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenDate$VariableFormField.setIsComplete();
		addField( screenDate$VariableFormField );
		StartName = new com.ibm.javart.CharItem( "StartName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( StartName );
		StartName$VariableFormField = new egl.ui.text.TuiField( "StartName$VariableFormField", this, StartName );
		StartName$VariableFormField.setLength(10);
		StartName$VariableFormField.setPosition(0,3,24);
		StartName$VariableFormField.setCurrentValue(0,"",true);
		StartName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		StartName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		StartName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		StartName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		StartName$VariableFormField.setUpperCase(true);
		StartName$VariableFormField.setIsComplete();
		addField( StartName$VariableFormField );
		setFormGroupClassName("egltui.opt1.custlist.xyzCL1FormGroup");
		setSize(24,80);
		setIsFloating(false);
		setPosition(1,1);
		setMessageField(formMSG$VariableFormField);
		addDeviceSize(24,80);
		signature( "Tegltui/opt1/custlist/custList;" );
	}
	
}
