// Generated at Mon Jun 11 21:44:44 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.logon;

public class xyzLogFormGroup$Login extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $1_1$ConstantFormField;
	public egl.ui.text.TuiField $2_1$ConstantFormField;
	public egl.ui.text.TuiField $3_1$ConstantFormField;
	public egl.ui.text.TuiField $4_1$ConstantFormField;
	public egl.ui.text.TuiField $5_1$ConstantFormField;
	public egl.ui.text.TuiField $6_1$ConstantFormField;
	public egl.ui.text.TuiField $7_1$ConstantFormField;
	public egl.ui.text.TuiField $8_1$ConstantFormField;
	public egl.ui.text.TuiField $9_1$ConstantFormField;
	public egl.ui.text.TuiField $10_1$ConstantFormField;
	public egl.ui.text.TuiField $11_1$ConstantFormField;
	public egl.ui.text.TuiField $12_1$ConstantFormField;
	public egl.ui.text.TuiField $13_1$ConstantFormField;
	public egl.ui.text.TuiField $14_1$ConstantFormField;
	public egl.ui.text.TuiField $17_20$ConstantFormField;
	public egl.ui.text.TuiField $18_19$ConstantFormField;
	public egl.ui.text.TuiField $16_18$ConstantFormField;
	public egl.ui.text.TuiField $20_19$ConstantFormField;
	public egl.ui.text.TuiField $15_1$ConstantFormField;
	public egl.ui.text.TuiField $16_1$ConstantFormField;
	public egl.ui.text.TuiField $17_1$ConstantFormField;
	public egl.ui.text.TuiField $18_1$ConstantFormField;
	public egl.ui.text.TuiField $19_1$ConstantFormField;
	public egl.ui.text.TuiField $20_1$ConstantFormField;
	public egl.ui.text.TuiField $21_1$ConstantFormField;
	public egl.ui.text.TuiField $22_1$ConstantFormField;
	public egl.ui.text.TuiField $24_1$ConstantFormField;
	public egl.ui.text.TuiField $23_1$ConstantFormField;
	public egl.ui.text.TuiField $22_74$ConstantFormField;
	public egl.ui.text.TuiField $21_75$ConstantFormField;
	public egl.ui.text.TuiField $20_75$ConstantFormField;
	public egl.ui.text.TuiField $19_75$ConstantFormField;
	public egl.ui.text.TuiField $18_75$ConstantFormField;
	public egl.ui.text.TuiField $17_75$ConstantFormField;
	public egl.ui.text.TuiField $16_74$ConstantFormField;
	public egl.ui.text.TuiField $15_74$ConstantFormField;
	public com.ibm.javart.CharValue userName;
	public egl.ui.text.TuiField userName$VariableFormField;
	public com.ibm.javart.CharValue passWord;
	public egl.ui.text.TuiField passWord$VariableFormField;
	public com.ibm.javart.CharValue todaysDate;
	public egl.ui.text.TuiField todaysDate$VariableFormField;
	public com.ibm.javart.CharValue mapTime;
	public egl.ui.text.TuiField mapTime$VariableFormField;
	public com.ibm.javart.CharValue formMSG;
	public egl.ui.text.TuiField formMSG$VariableFormField;
	public com.ibm.javart.CharValue fkeyLine1;
	public egl.ui.text.TuiField fkeyLine1$VariableFormField;
	
	public xyzLogFormGroup$Login( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$1_1$ConstantFormField = new egl.ui.text.TuiField( "$1_1$ConstantFormField", this, null );
		$1_1$ConstantFormField.setLength(78);
		$1_1$ConstantFormField.setPosition(0,1,1);
		$1_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$1_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$1_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$1_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$1_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$1_1$ConstantFormField.setIsComplete();
		addField( $1_1$ConstantFormField );
		$2_1$ConstantFormField = new egl.ui.text.TuiField( "$2_1$ConstantFormField", this, null );
		$2_1$ConstantFormField.setLength(78);
		$2_1$ConstantFormField.setPosition(0,2,1);
		$2_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$2_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$2_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$2_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$2_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$2_1$ConstantFormField.setIsComplete();
		addField( $2_1$ConstantFormField );
		$3_1$ConstantFormField = new egl.ui.text.TuiField( "$3_1$ConstantFormField", this, null );
		$3_1$ConstantFormField.setLength(78);
		$3_1$ConstantFormField.setPosition(0,3,1);
		$3_1$ConstantFormField.setCurrentValue(0,"****                                                                     ****",true);
		$3_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$3_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$3_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$3_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$3_1$ConstantFormField.setIsComplete();
		addField( $3_1$ConstantFormField );
		$4_1$ConstantFormField = new egl.ui.text.TuiField( "$4_1$ConstantFormField", this, null );
		$4_1$ConstantFormField.setLength(78);
		$4_1$ConstantFormField.setPosition(0,4,1);
		$4_1$ConstantFormField.setCurrentValue(0,"**      XXXXX     XXXXX    YYYY    YYYY   ZZZZZZZZZZZ                     ***",true);
		$4_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$4_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$4_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$4_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$4_1$ConstantFormField.setIsComplete();
		addField( $4_1$ConstantFormField );
		$5_1$ConstantFormField = new egl.ui.text.TuiField( "$5_1$ConstantFormField", this, null );
		$5_1$ConstantFormField.setLength(78);
		$5_1$ConstantFormField.setPosition(0,5,1);
		$5_1$ConstantFormField.setCurrentValue(0,"*        XXXXX   XXXXX      YYYY  YYYY    ZZZZZZZZZZZ                      **",true);
		$5_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$5_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$5_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_1$ConstantFormField.setIsComplete();
		addField( $5_1$ConstantFormField );
		$6_1$ConstantFormField = new egl.ui.text.TuiField( "$6_1$ConstantFormField", this, null );
		$6_1$ConstantFormField.setLength(78);
		$6_1$ConstantFormField.setPosition(0,6,1);
		$6_1$ConstantFormField.setCurrentValue(0,"*         XXXXX XXXXX        YYYY YYY          ZZZZZ                        *",true);
		$6_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$6_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$6_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$6_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$6_1$ConstantFormField.setIsComplete();
		addField( $6_1$ConstantFormField );
		$7_1$ConstantFormField = new egl.ui.text.TuiField( "$7_1$ConstantFormField", this, null );
		$7_1$ConstantFormField.setLength(78);
		$7_1$ConstantFormField.setPosition(0,7,1);
		$7_1$ConstantFormField.setCurrentValue(0,"*          XXXXXXXXX          YYYYYY          ZZZZZ      cccc     oooo      *",true);
		$7_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$7_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$7_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$7_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$7_1$ConstantFormField.setIsComplete();
		addField( $7_1$ConstantFormField );
		$8_1$ConstantFormField = new egl.ui.text.TuiField( "$8_1$ConstantFormField", this, null );
		$8_1$ConstantFormField.setLength(78);
		$8_1$ConstantFormField.setPosition(0,8,1);
		$8_1$ConstantFormField.setCurrentValue(0,"*         XXXXX XXXXX          YYYY         ZZZZZ      ccc ccc   ooo ooo    *",true);
		$8_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$8_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$8_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$8_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$8_1$ConstantFormField.setIsComplete();
		addField( $8_1$ConstantFormField );
		$9_1$ConstantFormField = new egl.ui.text.TuiField( "$9_1$ConstantFormField", this, null );
		$9_1$ConstantFormField.setLength(78);
		$9_1$ConstantFormField.setPosition(0,9,1);
		$9_1$ConstantFormField.setCurrentValue(0,"*        XXXXX   XXXXX         YYYY       ZZZZZ       ccc       ooo   ooo   *",true);
		$9_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$9_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$9_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$9_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$9_1$ConstantFormField.setIsComplete();
		addField( $9_1$ConstantFormField );
		$10_1$ConstantFormField = new egl.ui.text.TuiField( "$10_1$ConstantFormField", this, null );
		$10_1$ConstantFormField.setLength(78);
		$10_1$ConstantFormField.setPosition(0,10,1);
		$10_1$ConstantFormField.setCurrentValue(0,"**     XXXXX       XXXXX       YYYY     ZZZZZZZZZZZZ  ccc ccc   ooo ooo    **",true);
		$10_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$10_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$10_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$10_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$10_1$ConstantFormField.setIsComplete();
		addField( $10_1$ConstantFormField );
		$11_1$ConstantFormField = new egl.ui.text.TuiField( "$11_1$ConstantFormField", this, null );
		$11_1$ConstantFormField.setLength(78);
		$11_1$ConstantFormField.setPosition(0,11,1);
		$11_1$ConstantFormField.setCurrentValue(0,"***   XXXXX          XXXXX     YYYY     ZZZZZZZZZZZZ   cccc      oooo.    ***",true);
		$11_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$11_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$11_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$11_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$11_1$ConstantFormField.setIsComplete();
		addField( $11_1$ConstantFormField );
		$12_1$ConstantFormField = new egl.ui.text.TuiField( "$12_1$ConstantFormField", this, null );
		$12_1$ConstantFormField.setLength(78);
		$12_1$ConstantFormField.setPosition(0,12,1);
		$12_1$ConstantFormField.setCurrentValue(0,"****                                                                     ****",true);
		$12_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$12_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$12_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$12_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$12_1$ConstantFormField.setIsComplete();
		addField( $12_1$ConstantFormField );
		$13_1$ConstantFormField = new egl.ui.text.TuiField( "$13_1$ConstantFormField", this, null );
		$13_1$ConstantFormField.setLength(78);
		$13_1$ConstantFormField.setPosition(0,13,1);
		$13_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$13_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$13_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$13_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$13_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$13_1$ConstantFormField.setIsComplete();
		addField( $13_1$ConstantFormField );
		$14_1$ConstantFormField = new egl.ui.text.TuiField( "$14_1$ConstantFormField", this, null );
		$14_1$ConstantFormField.setLength(78);
		$14_1$ConstantFormField.setPosition(0,14,1);
		$14_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$14_1$ConstantFormField.setColor(0,egl.ui.ColorKind.green);
		$14_1$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$14_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$14_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_1$ConstantFormField.setIsComplete();
		addField( $14_1$ConstantFormField );
		$17_20$ConstantFormField = new egl.ui.text.TuiField( "$17_20$ConstantFormField", this, null );
		$17_20$ConstantFormField.setLength(8);
		$17_20$ConstantFormField.setPosition(0,17,20);
		$17_20$ConstantFormField.setCurrentValue(0,"User ID:",true);
		$17_20$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$17_20$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$17_20$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$17_20$ConstantFormField.setIsComplete();
		addField( $17_20$ConstantFormField );
		$18_19$ConstantFormField = new egl.ui.text.TuiField( "$18_19$ConstantFormField", this, null );
		$18_19$ConstantFormField.setLength(9);
		$18_19$ConstantFormField.setPosition(0,18,19);
		$18_19$ConstantFormField.setCurrentValue(0,"Password:",true);
		$18_19$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$18_19$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$18_19$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$18_19$ConstantFormField.setIsComplete();
		addField( $18_19$ConstantFormField );
		$16_18$ConstantFormField = new egl.ui.text.TuiField( "$16_18$ConstantFormField", this, null );
		$16_18$ConstantFormField.setLength(28);
		$16_18$ConstantFormField.setPosition(0,16,18);
		$16_18$ConstantFormField.setCurrentValue(0,"To Login, please enter your",true);
		$16_18$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$16_18$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$16_18$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_18$ConstantFormField.setIsComplete();
		addField( $16_18$ConstantFormField );
		$20_19$ConstantFormField = new egl.ui.text.TuiField( "$20_19$ConstantFormField", this, null );
		$20_19$ConstantFormField.setLength(24);
		$20_19$ConstantFormField.setPosition(0,20,19);
		$20_19$ConstantFormField.setCurrentValue(0,"Press Enter to continue",true);
		$20_19$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$20_19$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$20_19$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$20_19$ConstantFormField.setIsComplete();
		addField( $20_19$ConstantFormField );
		$15_1$ConstantFormField = new egl.ui.text.TuiField( "$15_1$ConstantFormField", this, null );
		$15_1$ConstantFormField.setLength(5);
		$15_1$ConstantFormField.setPosition(0,15,1);
		$15_1$ConstantFormField.setCurrentValue(0,"****",true);
		$15_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$15_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$15_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_1$ConstantFormField.setIsComplete();
		addField( $15_1$ConstantFormField );
		$16_1$ConstantFormField = new egl.ui.text.TuiField( "$16_1$ConstantFormField", this, null );
		$16_1$ConstantFormField.setLength(3);
		$16_1$ConstantFormField.setPosition(0,16,1);
		$16_1$ConstantFormField.setCurrentValue(0,"***",true);
		$16_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$16_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$16_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_1$ConstantFormField.setIsComplete();
		addField( $16_1$ConstantFormField );
		$17_1$ConstantFormField = new egl.ui.text.TuiField( "$17_1$ConstantFormField", this, null );
		$17_1$ConstantFormField.setLength(3);
		$17_1$ConstantFormField.setPosition(0,17,1);
		$17_1$ConstantFormField.setCurrentValue(0,"**",true);
		$17_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$17_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$17_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$17_1$ConstantFormField.setIsComplete();
		addField( $17_1$ConstantFormField );
		$18_1$ConstantFormField = new egl.ui.text.TuiField( "$18_1$ConstantFormField", this, null );
		$18_1$ConstantFormField.setLength(3);
		$18_1$ConstantFormField.setPosition(0,18,1);
		$18_1$ConstantFormField.setCurrentValue(0,"*",true);
		$18_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$18_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$18_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$18_1$ConstantFormField.setIsComplete();
		addField( $18_1$ConstantFormField );
		$19_1$ConstantFormField = new egl.ui.text.TuiField( "$19_1$ConstantFormField", this, null );
		$19_1$ConstantFormField.setLength(3);
		$19_1$ConstantFormField.setPosition(0,19,1);
		$19_1$ConstantFormField.setCurrentValue(0,"*",true);
		$19_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$19_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$19_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$19_1$ConstantFormField.setIsComplete();
		addField( $19_1$ConstantFormField );
		$20_1$ConstantFormField = new egl.ui.text.TuiField( "$20_1$ConstantFormField", this, null );
		$20_1$ConstantFormField.setLength(3);
		$20_1$ConstantFormField.setPosition(0,20,1);
		$20_1$ConstantFormField.setCurrentValue(0,"**",true);
		$20_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$20_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$20_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$20_1$ConstantFormField.setIsComplete();
		addField( $20_1$ConstantFormField );
		$21_1$ConstantFormField = new egl.ui.text.TuiField( "$21_1$ConstantFormField", this, null );
		$21_1$ConstantFormField.setLength(3);
		$21_1$ConstantFormField.setPosition(0,21,1);
		$21_1$ConstantFormField.setCurrentValue(0,"***",true);
		$21_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$21_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$21_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$21_1$ConstantFormField.setIsComplete();
		addField( $21_1$ConstantFormField );
		$22_1$ConstantFormField = new egl.ui.text.TuiField( "$22_1$ConstantFormField", this, null );
		$22_1$ConstantFormField.setLength(4);
		$22_1$ConstantFormField.setPosition(0,22,1);
		$22_1$ConstantFormField.setCurrentValue(0,"****",true);
		$22_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$22_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$22_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$22_1$ConstantFormField.setIsComplete();
		addField( $22_1$ConstantFormField );
		$24_1$ConstantFormField = new egl.ui.text.TuiField( "$24_1$ConstantFormField", this, null );
		$24_1$ConstantFormField.setLength(78);
		$24_1$ConstantFormField.setPosition(0,24,1);
		$24_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$24_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$24_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$24_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$24_1$ConstantFormField.setIsComplete();
		addField( $24_1$ConstantFormField );
		$23_1$ConstantFormField = new egl.ui.text.TuiField( "$23_1$ConstantFormField", this, null );
		$23_1$ConstantFormField.setLength(78);
		$23_1$ConstantFormField.setPosition(0,23,1);
		$23_1$ConstantFormField.setCurrentValue(0,"*****************************************************************************",true);
		$23_1$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$23_1$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$23_1$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$23_1$ConstantFormField.setIsComplete();
		addField( $23_1$ConstantFormField );
		$22_74$ConstantFormField = new egl.ui.text.TuiField( "$22_74$ConstantFormField", this, null );
		$22_74$ConstantFormField.setLength(4);
		$22_74$ConstantFormField.setPosition(0,22,74);
		$22_74$ConstantFormField.setCurrentValue(0,"****",true);
		$22_74$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$22_74$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$22_74$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$22_74$ConstantFormField.setIsComplete();
		addField( $22_74$ConstantFormField );
		$21_75$ConstantFormField = new egl.ui.text.TuiField( "$21_75$ConstantFormField", this, null );
		$21_75$ConstantFormField.setLength(3);
		$21_75$ConstantFormField.setPosition(0,21,75);
		$21_75$ConstantFormField.setCurrentValue(0,"***",true);
		$21_75$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$21_75$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$21_75$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$21_75$ConstantFormField.setIsComplete();
		addField( $21_75$ConstantFormField );
		$20_75$ConstantFormField = new egl.ui.text.TuiField( "$20_75$ConstantFormField", this, null );
		$20_75$ConstantFormField.setLength(3);
		$20_75$ConstantFormField.setPosition(0,20,75);
		$20_75$ConstantFormField.setCurrentValue(0," **",true);
		$20_75$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$20_75$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$20_75$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$20_75$ConstantFormField.setIsComplete();
		addField( $20_75$ConstantFormField );
		$19_75$ConstantFormField = new egl.ui.text.TuiField( "$19_75$ConstantFormField", this, null );
		$19_75$ConstantFormField.setLength(3);
		$19_75$ConstantFormField.setPosition(0,19,75);
		$19_75$ConstantFormField.setCurrentValue(0,"  *",true);
		$19_75$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$19_75$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$19_75$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$19_75$ConstantFormField.setIsComplete();
		addField( $19_75$ConstantFormField );
		$18_75$ConstantFormField = new egl.ui.text.TuiField( "$18_75$ConstantFormField", this, null );
		$18_75$ConstantFormField.setLength(3);
		$18_75$ConstantFormField.setPosition(0,18,75);
		$18_75$ConstantFormField.setCurrentValue(0,"  *",true);
		$18_75$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$18_75$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$18_75$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$18_75$ConstantFormField.setIsComplete();
		addField( $18_75$ConstantFormField );
		$17_75$ConstantFormField = new egl.ui.text.TuiField( "$17_75$ConstantFormField", this, null );
		$17_75$ConstantFormField.setLength(3);
		$17_75$ConstantFormField.setPosition(0,17,75);
		$17_75$ConstantFormField.setCurrentValue(0," **",true);
		$17_75$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$17_75$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$17_75$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$17_75$ConstantFormField.setIsComplete();
		addField( $17_75$ConstantFormField );
		$16_74$ConstantFormField = new egl.ui.text.TuiField( "$16_74$ConstantFormField", this, null );
		$16_74$ConstantFormField.setLength(4);
		$16_74$ConstantFormField.setPosition(0,16,74);
		$16_74$ConstantFormField.setCurrentValue(0," ***",true);
		$16_74$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$16_74$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$16_74$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_74$ConstantFormField.setIsComplete();
		addField( $16_74$ConstantFormField );
		$15_74$ConstantFormField = new egl.ui.text.TuiField( "$15_74$ConstantFormField", this, null );
		$15_74$ConstantFormField.setLength(4);
		$15_74$ConstantFormField.setPosition(0,15,74);
		$15_74$ConstantFormField.setCurrentValue(0,"****",true);
		$15_74$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$15_74$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$15_74$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$15_74$ConstantFormField.setIsComplete();
		addField( $15_74$ConstantFormField );
		userName = new com.ibm.javart.CharItem( "userName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( userName );
		userName$VariableFormField = new egl.ui.text.TuiField( "userName$VariableFormField", this, userName );
		userName$VariableFormField.setLength(10);
		userName$VariableFormField.setPosition(0,17,30);
		userName$VariableFormField.setCurrentValue(0,"",true);
		userName$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		userName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		userName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		userName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		userName$VariableFormField.setIsComplete();
		addField( userName$VariableFormField );
		passWord = new com.ibm.javart.CharItem( "passWord", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( passWord );
		passWord$VariableFormField = new egl.ui.text.TuiField( "passWord$VariableFormField", this, passWord );
		passWord$VariableFormField.setLength(10);
		passWord$VariableFormField.setPosition(0,18,30);
		passWord$VariableFormField.setCurrentValue(0,"",true);
		passWord$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		passWord$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		passWord$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		passWord$VariableFormField.setJustify(egl.ui.AlignKind.left);
		passWord$VariableFormField.setIsComplete();
		addField( passWord$VariableFormField );
		todaysDate = new com.ibm.javart.CharItem( "todaysDate", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( todaysDate );
		todaysDate$VariableFormField = new egl.ui.text.TuiField( "todaysDate$VariableFormField", this, todaysDate );
		todaysDate$VariableFormField.setLength(10);
		todaysDate$VariableFormField.setPosition(0,15,60);
		todaysDate$VariableFormField.setCurrentValue(0,"",true);
		todaysDate$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		todaysDate$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		todaysDate$VariableFormField.setJustify(egl.ui.AlignKind.left);
		todaysDate$VariableFormField.setIsComplete();
		addField( todaysDate$VariableFormField );
		mapTime = new com.ibm.javart.CharItem( "mapTime", com.ibm.javart.Value.SQL_NOT_NULLABLE, 8, true, "C8;" );
		add( mapTime );
		mapTime$VariableFormField = new egl.ui.text.TuiField( "mapTime$VariableFormField", this, mapTime );
		mapTime$VariableFormField.setLength(8);
		mapTime$VariableFormField.setPosition(0,16,60);
		mapTime$VariableFormField.setCurrentValue(0,"",true);
		mapTime$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		mapTime$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		mapTime$VariableFormField.setJustify(egl.ui.AlignKind.left);
		mapTime$VariableFormField.setIsComplete();
		addField( mapTime$VariableFormField );
		formMSG = new com.ibm.javart.CharItem( "formMSG", com.ibm.javart.Value.SQL_NOT_NULLABLE, 68, true, "C68;" );
		add( formMSG );
		formMSG$VariableFormField = new egl.ui.text.TuiField( "formMSG$VariableFormField", this, formMSG );
		formMSG$VariableFormField.setLength(68);
		formMSG$VariableFormField.setPosition(0,21,6);
		formMSG$VariableFormField.setCurrentValue(0,"",true);
		formMSG$VariableFormField.setHighlight(0,egl.ui.HighlightKind.noHighlight);
		formMSG$VariableFormField.setColor(0,egl.ui.ColorKind.red);
		formMSG$VariableFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		formMSG$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		formMSG$VariableFormField.setJustify(egl.ui.AlignKind.left);
		formMSG$VariableFormField.setIsComplete();
		addField( formMSG$VariableFormField );
		fkeyLine1 = new com.ibm.javart.CharItem( "fkeyLine1", com.ibm.javart.Value.SQL_NOT_NULLABLE, 67, true, "C67;" );
		add( fkeyLine1 );
		fkeyLine1$VariableFormField = new egl.ui.text.TuiField( "fkeyLine1$VariableFormField", this, fkeyLine1 );
		fkeyLine1$VariableFormField.setLength(67);
		fkeyLine1$VariableFormField.setPosition(0,22,6);
		fkeyLine1$VariableFormField.setCurrentValue(0,"",true);
		fkeyLine1$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		fkeyLine1$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		fkeyLine1$VariableFormField.setJustify(egl.ui.AlignKind.left);
		fkeyLine1$VariableFormField.setIsComplete();
		addField( fkeyLine1$VariableFormField );
		setFormGroupClassName("egltui.logon.xyzLogFormGroup");
		setSize(24,80);
		setIsFloating(false);
		setPosition(1,1);
		setMessageField(formMSG$VariableFormField);
		addDeviceSize(24,80);
		signature( "Tegltui/logon/Login;" );
	}
	
}
