// Generated at Mon Jun 11 21:44:44 CEST 2018 by EGL 8.0.0.v20150827_1902
// No APARs installed.
package egltui.menu;

public class xyzMnuFormGroup$Menu extends egl.ui.text.TextForm
{
	private static final long serialVersionUID = 70L;
	
	public egl.ui.text.TuiField $1_34$ConstantFormField;
	public egl.ui.text.TuiField $14_25$ConstantFormField;
	public egl.ui.text.TuiField $16_21$ConstantFormField;
	public egl.ui.text.TuiField $5_4$ConstantFormField;
	public com.ibm.javart.CharValue screenName;
	public egl.ui.text.TuiField screenName$VariableFormField;
	public com.ibm.javart.CharValue screenDate;
	public egl.ui.text.TuiField screenDate$VariableFormField;
	public com.ibm.javart.CharValue ScreenTitle;
	public egl.ui.text.TuiField ScreenTitle$VariableFormField;
	public com.ibm.javart.ref.CharArrayRef MenuLine;
	public egl.ui.text.TuiField MenuLine$VariableFormField;
	public com.ibm.javart.SmallNumericValue MenuOption;
	public egl.ui.text.TuiField MenuOption$VariableFormField;
	public com.ibm.javart.CharValue formMSG;
	public egl.ui.text.TuiField formMSG$VariableFormField;
	public com.ibm.javart.CharValue fkeyLine2;
	public egl.ui.text.TuiField fkeyLine2$VariableFormField;
	public com.ibm.javart.CharValue firstname;
	public egl.ui.text.TuiField firstname$VariableFormField;
	
	public xyzMnuFormGroup$Menu( final com.ibm.javart.resources.Program ezeProgram, String ezeName ) throws com.ibm.javart.JavartException
	{
		super( ezeProgram, ezeName );
		$1_34$ConstantFormField = new egl.ui.text.TuiField( "$1_34$ConstantFormField", this, null );
		$1_34$ConstantFormField.setLength(14);
		$1_34$ConstantFormField.setPosition(0,1,34);
		$1_34$ConstantFormField.setCurrentValue(0,"XYZ Company",true);
		$1_34$ConstantFormField.setColor(0,egl.ui.ColorKind.yellow);
		$1_34$ConstantFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		$1_34$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$1_34$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$1_34$ConstantFormField.setIsComplete();
		addField( $1_34$ConstantFormField );
		$14_25$ConstantFormField = new egl.ui.text.TuiField( "$14_25$ConstantFormField", this, null );
		$14_25$ConstantFormField.setLength(10);
		$14_25$ConstantFormField.setPosition(0,14,25);
		$14_25$ConstantFormField.setCurrentValue(0,"Selection:",true);
		$14_25$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$14_25$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$14_25$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$14_25$ConstantFormField.setIsComplete();
		addField( $14_25$ConstantFormField );
		$16_21$ConstantFormField = new egl.ui.text.TuiField( "$16_21$ConstantFormField", this, null );
		$16_21$ConstantFormField.setLength(47);
		$16_21$ConstantFormField.setPosition(0,16,21);
		$16_21$ConstantFormField.setCurrentValue(0,"Type the Menu Item number and Press Enter",true);
		$16_21$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$16_21$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$16_21$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$16_21$ConstantFormField.setIsComplete();
		addField( $16_21$ConstantFormField );
		$5_4$ConstantFormField = new egl.ui.text.TuiField( "$5_4$ConstantFormField", this, null );
		$5_4$ConstantFormField.setPosition(0,5,4);
		$5_4$ConstantFormField.setCurrentValue(0,"Welcome,",true);
		$5_4$ConstantFormField.setColor(0,egl.ui.ColorKind.cyan);
		$5_4$ConstantFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		$5_4$ConstantFormField.setJustify(egl.ui.AlignKind.left);
		$5_4$ConstantFormField.setIsComplete();
		addField( $5_4$ConstantFormField );
		screenName = new com.ibm.javart.CharItem( "screenName", com.ibm.javart.Value.SQL_NOT_NULLABLE, 9, true, "C9;" );
		add( screenName );
		screenName$VariableFormField = new egl.ui.text.TuiField( "screenName$VariableFormField", this, screenName );
		screenName$VariableFormField.setLength(9);
		screenName$VariableFormField.setPosition(0,1,1);
		screenName$VariableFormField.setCurrentValue(0,"",true);
		screenName$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenName$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenName$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenName$VariableFormField.setIsComplete();
		addField( screenName$VariableFormField );
		screenDate = new com.ibm.javart.CharItem( "screenDate", com.ibm.javart.Value.SQL_NOT_NULLABLE, 10, true, "C10;" );
		add( screenDate );
		screenDate$VariableFormField = new egl.ui.text.TuiField( "screenDate$VariableFormField", this, screenDate );
		screenDate$VariableFormField.setLength(10);
		screenDate$VariableFormField.setPosition(0,1,69);
		screenDate$VariableFormField.setCurrentValue(0,"",true);
		screenDate$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		screenDate$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		screenDate$VariableFormField.setJustify(egl.ui.AlignKind.left);
		screenDate$VariableFormField.setIsComplete();
		addField( screenDate$VariableFormField );
		ScreenTitle = new com.ibm.javart.CharItem( "ScreenTitle", com.ibm.javart.Value.SQL_NOT_NULLABLE, 50, true, "C50;" );
		add( ScreenTitle );
		ScreenTitle$VariableFormField = new egl.ui.text.TuiField( "ScreenTitle$VariableFormField", this, ScreenTitle );
		ScreenTitle$VariableFormField.setLength(50);
		ScreenTitle$VariableFormField.setPosition(0,2,15);
		ScreenTitle$VariableFormField.setCurrentValue(0,"",true);
		ScreenTitle$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		ScreenTitle$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		ScreenTitle$VariableFormField.setJustify(egl.ui.AlignKind.left);
		ScreenTitle$VariableFormField.setIsComplete();
		addField( ScreenTitle$VariableFormField );
		MenuLine = new com.ibm.javart.ref.CharArrayRef( "MenuLine", new com.ibm.javart.arrays.CharArray( "MenuLine", ezeProgram, 5, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 35, "1C35;" ), "1C35;" ){
			private static final long serialVersionUID = 70L;
			
			public void createNewValue( com.ibm.javart.resources.Program ezeProgram ) throws com.ibm.javart.JavartException
			{
				value = new com.ibm.javart.arrays.CharArray( "MenuLine", ezeProgram, 0, 10, Integer.MAX_VALUE, com.ibm.javart.Value.SQL_NOT_NULLABLE, 35, "1C35;" );
			}
		};
		add( MenuLine );
		MenuLine$VariableFormField = new egl.ui.text.TuiField( "MenuLine$VariableFormField", this, MenuLine );
		MenuLine$VariableFormField.setLength(35);
		MenuLine$VariableFormField.setPosition(0,8,25);
		MenuLine$VariableFormField.setCurrentValue(0,"",true);
		MenuLine$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		MenuLine$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		MenuLine$VariableFormField.setPosition(1,9,25);
		MenuLine$VariableFormField.setCurrentValue(1,"",true);
		MenuLine$VariableFormField.setColor(1,egl.ui.ColorKind.green);
		MenuLine$VariableFormField.setProtect(1,egl.ui.text.ProtectKind.skipProtect);
		MenuLine$VariableFormField.setPosition(2,10,25);
		MenuLine$VariableFormField.setCurrentValue(2,"",true);
		MenuLine$VariableFormField.setColor(2,egl.ui.ColorKind.green);
		MenuLine$VariableFormField.setProtect(2,egl.ui.text.ProtectKind.skipProtect);
		MenuLine$VariableFormField.setPosition(3,11,25);
		MenuLine$VariableFormField.setCurrentValue(3,"",true);
		MenuLine$VariableFormField.setColor(3,egl.ui.ColorKind.green);
		MenuLine$VariableFormField.setProtect(3,egl.ui.text.ProtectKind.skipProtect);
		MenuLine$VariableFormField.setPosition(4,12,25);
		MenuLine$VariableFormField.setCurrentValue(4,"",true);
		MenuLine$VariableFormField.setColor(4,egl.ui.ColorKind.green);
		MenuLine$VariableFormField.setProtect(4,egl.ui.text.ProtectKind.skipProtect);
		MenuLine$VariableFormField.setJustify(egl.ui.AlignKind.left);
		MenuLine$VariableFormField.setIsComplete();
		addField( MenuLine$VariableFormField );
		MenuOption = new com.ibm.javart.SmallNumericItem( "MenuOption", com.ibm.javart.Value.SQL_NOT_NULLABLE, 1, com.ibm.javart.Constants.EGL_TYPE_NUM, "N1:0;" );
		add( MenuOption );
		MenuOption$VariableFormField = new egl.ui.text.TuiField( "MenuOption$VariableFormField", this, MenuOption );
		MenuOption$VariableFormField.setLength(1);
		MenuOption$VariableFormField.setPosition(0,14,36);
		MenuOption$VariableFormField.setCurrentValue(0,"",true);
		MenuOption$VariableFormField.setHighlight(0,egl.ui.HighlightKind.underline);
		MenuOption$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		MenuOption$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.noProtect);
		MenuOption$VariableFormField.setJustify(egl.ui.AlignKind.right);
		MenuOption$VariableFormField.setInputRequired(true);
		MenuOption$VariableFormField.setValidValues(new Object[][]{{java.lang.Long.valueOf(1L),java.lang.Long.valueOf(5L)}});
		MenuOption$VariableFormField.setIsComplete();
		addField( MenuOption$VariableFormField );
		formMSG = new com.ibm.javart.CharItem( "formMSG", com.ibm.javart.Value.SQL_NOT_NULLABLE, 76, true, "C76;" );
		add( formMSG );
		formMSG$VariableFormField = new egl.ui.text.TuiField( "formMSG$VariableFormField", this, formMSG );
		formMSG$VariableFormField.setLength(76);
		formMSG$VariableFormField.setPosition(0,22,3);
		formMSG$VariableFormField.setCurrentValue(0,"",true);
		formMSG$VariableFormField.setHighlight(0,egl.ui.HighlightKind.noHighlight);
		formMSG$VariableFormField.setColor(0,egl.ui.ColorKind.red);
		formMSG$VariableFormField.setIntensity(0,egl.ui.IntensityKind.bold);
		formMSG$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		formMSG$VariableFormField.setJustify(egl.ui.AlignKind.left);
		formMSG$VariableFormField.setIsComplete();
		addField( formMSG$VariableFormField );
		fkeyLine2 = new com.ibm.javart.CharItem( "fkeyLine2", com.ibm.javart.Value.SQL_NOT_NULLABLE, 78, true, "C78;" );
		add( fkeyLine2 );
		fkeyLine2$VariableFormField = new egl.ui.text.TuiField( "fkeyLine2$VariableFormField", this, fkeyLine2 );
		fkeyLine2$VariableFormField.setLength(78);
		fkeyLine2$VariableFormField.setPosition(0,24,1);
		fkeyLine2$VariableFormField.setCurrentValue(0,"",true);
		fkeyLine2$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		fkeyLine2$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		fkeyLine2$VariableFormField.setJustify(egl.ui.AlignKind.left);
		fkeyLine2$VariableFormField.setIsComplete();
		addField( fkeyLine2$VariableFormField );
		firstname = new com.ibm.javart.CharItem( "firstname", com.ibm.javart.Value.SQL_NOT_NULLABLE, 20, true, "C20;" );
		add( firstname );
		firstname$VariableFormField = new egl.ui.text.TuiField( "firstname$VariableFormField", this, firstname );
		firstname$VariableFormField.setLength(20);
		firstname$VariableFormField.setPosition(0,5,13);
		firstname$VariableFormField.setCurrentValue(0,"",true);
		firstname$VariableFormField.setColor(0,egl.ui.ColorKind.green);
		firstname$VariableFormField.setProtect(0,egl.ui.text.ProtectKind.skipProtect);
		firstname$VariableFormField.setJustify(egl.ui.AlignKind.left);
		firstname$VariableFormField.setIsComplete();
		addField( firstname$VariableFormField );
		setFormGroupClassName("egltui.menu.xyzMnuFormGroup");
		setSize(24,80);
		setIsFloating(false);
		setPosition(1,1);
		setValidationBypassKeys(new com.ibm.javart.IntValue[]{egl.ui.PFKeyKind.pf2,egl.ui.PFKeyKind.pf3});
		setHelpKey(egl.ui.PFKeyKind.pf1);
		setHelpFormId("xyzMnuFormGroup$Help1");
		setMessageField(formMSG$VariableFormField);
		addDeviceSize(24,80);
		signature( "Tegltui/menu/Menu;" );
	}
	
}
